### ISSUE TITLE
The security token included in the request is invalid.

### ISSUE THREAD

**Issue by vanghern** [aws/aws-lambda-dotnet#1122]
## Description
During testing, using Mock Lambda tool I'm getting this error:

Amazon.DynamoDBv2.AmazonDynamoDBException: The security token included in the request is invalid.
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData httpErrorResponse, HttpErrorResponseException exception, Stream responseStream) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\HttpErrorResponseExceptionHandler.cs:line 163
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\HttpErrorResponseExceptionHandler.cs:line 63
   at Amazon.Runtime.Internal.ExceptionHandler`1.Handle(IExecutionContext executionContext, Exception exception) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ExceptionHandler.cs:line 38
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 212
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 78
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 60
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 46
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 60
   at Amazon.Runtime.Internal.Signer.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\Signer.cs:line 39
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 60
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\EndpointDiscoveryHandler.cs:line 44
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 60
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CredentialsRetriever.cs:line 73
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 60
   at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\RetryHandler\RetryHandler.cs:line 77
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 60
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 46
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 60
   at Amazon.Runtime.Internal.EndpointResolver.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\EndpointResolver.cs:line 35
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 60
   at Amazon.Runtime.Internal.Marshaller.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\Marshaller.cs:line 38
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 60
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 46
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 60
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\ErrorCallbackHandler.cs:line 39
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 60
   at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\MetricsHandler.cs:line 40
   at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\RuntimePipeline.cs:line 136
   at Amazon.Runtime.AmazonServiceClient.Invoke[TResponse](AmazonWebServiceRequest request, InvokeOptionsBase options) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\AmazonServiceClient.cs:line 220
   at Amazon.DynamoDBv2.AmazonDynamoDBClient.DescribeTable(DescribeTableRequest request) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Generated\_netstandard\AmazonDynamoDBClient.cs:line 2462
   at Amazon.DynamoDBv2.DocumentModel.Table.DescribeTable(String tableName) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DocumentModel\Table.cs:line 335
   at Amazon.Runtime.Internal.Util.Cache`2.GetValueHelper(TKey key, Boolean& isStaleItem, Func`2 creator) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\Util\SdkCache.cs:line 428
   at Amazon.Runtime.Internal.Util.Cache`2.GetValue(TKey key, Func`2 creator, Boolean& isStaleItem) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\Util\SdkCache.cs:line 315
   at Amazon.DynamoDBv2.DocumentModel.Table.LoadTableInfo() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DocumentModel\Table.cs:line 134
   at Amazon.DynamoDBv2.DocumentModel.Table.LoadTable(IAmazonDynamoDB ddbClient, TableConfig config) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DocumentModel\Table.cs:line 413
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.GetUnconfiguredTable(String tableName) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DataModel\ContextInternal.cs:line 157
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.GetTargetTable(ItemStorageConfig storageConfig, DynamoDBFlatConfig flatConfig, DynamoDBConsumer consumer) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DataModel\ContextInternal.cs:line 112
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.ConvertScan[T](IEnumerable`1 conditions, DynamoDBOperationConfig operationConfig) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DataModel\ContextInternal.cs:line 1037
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.ScanAsync[T](IEnumerable`1 conditions, DynamoDBOperationConfig operationConfig) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DataModel\_async\Context.Async.cs:line 306
   at MobileTogether.Backend.Push.Handler.GetUserTenants(APIGatewayProxyRequest request, ILambdaContext context) in D:\Projects\tApps\backend\src\MobileTogether.Backend.Push\Handler.cs:line 503
   at Amazon.Lambda.TestTool.Runtime.LambdaExecutor.ProcessReturnAsync(ExecutionRequest request, Object lambdaReturnObject) in C:\codebuild\tmp\output\src581676283\src\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool\Runtime\LambdaExecutor.cs:line 141
   at Amazon.Lambda.TestTool.Runtime.LambdaExecutor.ExecuteAsync(ExecutionRequest request) in C:\codebuild\tmp\output\src581676283\src\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool\Runtime\LambdaExecutor.cs:line 62
---------------- Inner 1 Exception ------------
Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponse() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_netstandard\HttpRequestMessageFactory.cs:line 499
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:line 86
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 60
   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\Unmarshaller.cs:line 50
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 60
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 72

Expected result is a successful test of lambda function.

We have tested multiple versions of Credentials profiles, also played with aws-lamda-tools-defaults.json, and simply can't reach the dynamoDb. Error provided above is the latest/furthest, we managed to reach.

## Reproduction Steps

1. Install Mock Lambda Tools
2. Correctly set following properties in Credentials file:
- aws_access_key_id
- aws_secret_access_key
- role_arn
- aws_session_token
3. Correctly set following properties in aws-lamda-tools-defaults.json:
- framework
- function-runtime
- function-memory-size
- function-timeout
- function-handler
4. Launch Mock Lambda Tools from Visual Studio 2019
5. Press "Execute Function", using correct profile.

### Environment
* Build: AWS Lambda Core 2.1.0
* OS Info: Windows 10
* Build Environment: Visual Studio 2019
* Targeted .NET Platform:  .Net Core 3.1

**Comment by ashishdhingra** [comment]
Hi @vanghern,

Good morning.

Could you please share on how/where you have configured credentials? Please refer [Credential and profile resolution](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/creds-assign.html) for details on how credentials are resolved. Also looks like you are using session credentials since you are setting `aws_session_token` in credentials file. Temporary session credentials expire after certain duration, refer [Temporary security credentials in IAM](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp.html) for more details. After expiry, these need to be reset (refreshed) in the credentials file. The error you are getting indicates that your session credentials have expired and need to be reset. Hope this helps.

Thanks,
Ashish

**Comment by vanghern** [comment]
![image](https://user-images.githubusercontent.com/15214962/160378909-4ed5b48c-06b4-48c9-b88b-abc165b90a41.png)
Credentials on the screenshot.
Token is not expired. It's provided before the start of testing session, and is active for 12h.

**Comment by ashishdhingra** [comment]
@vanghern From the stack trace you shared earlier, looks like you are connecting to DynamoDB in your Lambda function and it is quite possible that the configured credentials does not have required permissions for the executed operation in the Lambda function. Could you check the IAM permissions for the temporary session credentials for DynamoDB operation?

Also, for further troubleshooting, please share the below:
1. Sample code snippet for the operation that is failing for the Lambda function.
2. Is it a simple Lambda function or serverless application?
3. The request that is sent via test tool. (i.e. JSON).
4. IAM permission policies for the temporary credentials.

Thanks,
Ashish

**Comment by vanghern** [comment]
@ashishdhingra 
Here are the details:
1. Piece of code that is failing
  var search = this._dynamoDb.ScanAsync<Tenant>(new ScanCondition[] { });
2. serverless application, but the config is set to check only 1 specific lambda function
3. it is empty
4. This is actually a good question. Could you please tell me how it should looks like, from Mock Tool perspective? I'm consuming this lambda on the frontend side and from Postman with Admin role, however, this Lamda doesn't have any specific policy defined (afaik).

**Comment by ashishdhingra** [comment]
Hi @vanghern,

Good afternoon.

Unfortunately, I'm unable to reproduce the issue. Used the following steps:
1. Created a simple DynamoDB Lambda project using AWS templates.
**Function.cs**
```C#

using Amazon.DynamoDBv2;
using Amazon.DynamoDBv2.DataModel;
using Amazon.Lambda.Core;
using Amazon.Lambda.DynamoDBEvents;
using System.Collections.Generic;

// Assembly attribute to enable the Lambda function's JSON input to be converted into a .NET class.
[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer))]

namespace TestLambdaDynamoDB_Issue1122
{
    public class Function
    {
        public void FunctionHandler(DynamoDBEvent dynamoEvent, ILambdaContext context)
        {
            using(var client=new AmazonDynamoDBClient())
            {
                DynamoDBContext dynamoDBContext = new DynamoDBContext(client);
                var scanResults = dynamoDBContext.ScanAsync<TestTable>(new List<ScanCondition>()).GetRemainingAsync().Result;
                context.Logger.LogLine($"Scan Results returned {scanResults.Count} records...");
            }
        }

        [DynamoDBTable("testtable")]
        public class TestTable
        {
            [DynamoDBHashKey]
            [DynamoDBProperty("id")]
            public string Id
            {
                get; set;
            }

            [DynamoDBProperty("name")]
            public string Name
            {
                get; set;
            }
        }
    }
}
```
**.csproj**
```XML
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
    <!-- This property makes the build directory similar to a publish directory and helps the AWS .NET Lambda Mock Test Tool find project dependencies. -->
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="2.1.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.3.0" />
    <PackageReference Include="Amazon.Lambda.DynamoDBEvents" Version="2.1.0" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.7.3.16" />
  </ItemGroup>
</Project>
```
**aws-lambda-tools-defaults.json**
```JSON
{
  "Information": [
    "This file provides default values for the deployment wizard inside Visual Studio and the AWS Lambda commands added to the .NET Core CLI.",
    "To learn more about the Lambda commands with the .NET Core CLI execute the following command at the command line in the project root directory.",
    "dotnet lambda help",
    "All the command line options for the Lambda command can be specified in this file."
  ],
  "profile": "default",
  "region": "us-east-2",
  "configuration": "Release",
  "framework": "netcoreapp3.1",
  "function-runtime": "dotnetcore3.1",
  "function-memory-size": 256,
  "function-timeout": 30,
  "function-handler": "TestLambdaDynamoDB_Issue1122::TestLambdaDynamoDB_Issue1122.Function::FunctionHandler"
}
```

2. Configured a new credentials profile with session credentials (these credentials have Admin access):
```
[test]
region=us-east-2
aws_access_key_id = <<access_key_id>>
aws_secret_access_key = <<secret_access_key>>
aws_session_token = <<session_token>><<e.g. IQoJb3JpZ2luX2VjEFMaCXVzLW...........Wbug2PV>>
toolkit_artifact_guid=6bf4ad6b-eda6-436c-85d2-f165db32d4f1
```
4. Created DynamoDB table `testtable` with `id` as partition key and `name` as sort key.
5. Installed the latest version of Lambda test tool `0.12.1`.
6. Debugged the application using Mock Lambda Test tool.
7. In Mock Lambda Test tool UI, selected the `test` profile in the `AWS Credential Profile` drop down list.
8. Clicked `Execute Function`

**RESULT:** It executes successfully returning the log output:
<img width="1306" alt="Screen Shot 2022-03-29 at 12 27 31 PM" src="https://user-images.githubusercontent.com/67916761/160691942-5a5be4ee-f21a-483c-9245-78267194b6d4.png">

Do you happen to have credentials configured in Windows **SDK Store** (`%USERPROFILE%\AppData\Local\AWSToolkit\RegisteredAccounts.json`) as documented at https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/credentials.html? If yes, try renaming the file to a different name (instead of deleting it) so that there is no conflict in credentials.

Thanks,
Ashish

**Comment by vanghern** [comment]
I'm not using Windows SDK Store for credentials. And also I don't know what else information I should provide, because your setup looks like mine, but for me it doesn't work.

**Comment by ashishdhingra** [comment]
> I'm not using Windows SDK Store for credentials. And also I don't know what else information I should provide, because your setup looks like mine, but for me it doesn't work.

@vanghern I'm unsure what more guidance to provide here. Looks like your credentials are resolved from a different location. You may try using a different Windows user for testing purposes, use AWS CLI to configure the named profile with the said Admin session credentials (taking note of default credentials profile chain location) and then use Mock Lambda Test tool to see if it works.

Thanks,
Ashish

**Comment by vanghern** [comment]
@ashishdhingra 
So here is the thing:
If I take the Credential file and create multiple profiles, with different configuration, and then I pick each of them in Mock Lambda Test Tool, I'm getting different errors. So Test Tool is definitely taking something from Configuration file.
However, we did a workaround - Hardcoded our credentials in .cs file and we are resolving MFA -> aws session token that way, and then we can access DynamoDb. On the other hand, we still have no idea what causes an issue, if we just use the Credential file.

**Comment by ashishdhingra** [comment]
> @ashishdhingra 
> 
> So here is the thing:
> 
> If I take the Credential file and create multiple profiles, with different configuration, and then I pick each of them in Mock Lambda Test Tool, I'm getting different errors. So Test Tool is definitely taking something from Configuration file.
> 
> However, we did a workaround - Hardcoded our credentials in .cs file and we are resolving MFA -> aws session token that way, and then we can access DynamoDb. On the other hand, we still have no idea what causes an issue, if we just use the Credential file.

@vanghern Do you happen to have duplicate parameter names in the same profile by any chance? I have seen issues in such cases, e.g., have duplicated region parameter. Also did you try using a different user profile with clean state as mentioned in my previous comment? I'm unsure on what more guidance could be provided here.
