### ISSUE TITLE
Does Lambda support async operations for ASP.Net Core?

### ISSUE THREAD

**Issue by strofimo** [aws/aws-lambda-dotnet#128]
Hi,

I have 2 ASP.net Core Web Api projects in my solution. They both use the same EF DBContext which point to MSSQL RDS instance. Both projects are pushed to AWS as serverless. 
First instance just do CRUD operations on DB without any issues. In CloudWatch log I see something like this:

> 18:37:01
> [Debug] Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory: TRACKED: False (QueryContext queryContext) => IEnumerable<Error> _ShapedQuery( queryContext: queryContext, shaperCommandContext: SelectExpression: SELECT [e].[Id], [e].[Code], [e].[Message] FROM [Errors] AS [e] , shaper: UnbufferedEntityShaper<Error> )
> [Debug] Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory: TRACKED: False
> (QueryContext queryContext) => IEnumerable<Error> _ShapedQuery(
> queryContext: queryContext, 
> shaperCommandContext: SelectExpression: 
> SELECT [e].[Id], [e].[Code], [e].[Message]
> FROM [Errors] AS [e]
> , 
> shaper: UnbufferedEntityShaper<Error>
> )
> 
> 18:37:01
> [Debug] Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection: Opening connection to database 'removed' on server 'removed'.
> 18:37:05
> [100m[32minfo[39m[0m: Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory[1]

Second project use some Identity capability of the same DBContext and it doesn't work:

> 19:05:15
> [Debug] Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory: TRACKED: True (QueryContext queryContext) => IAsyncEnumerable<IdentityRole> _ToSequence( task: Task<IdentityRole> _FirstOrDefault( source: IAsyncEnumerable<IdentityRole> _ShapedQuery( queryContext: queryContext, shaperCommandContext: SelectExpression:
> [Debug] Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory: TRACKED: True
> (QueryContext queryContext) => IAsyncEnumerable<IdentityRole> _ToSequence(
> task: Task<IdentityRole> _FirstOrDefault(
> source: IAsyncEnumerable<IdentityRole> _ShapedQuery(
> queryContext: queryContext, 
> shaperCommandContext: SelectExpression: 
> SELECT TOP(1) [r].[Id], [r].[ConcurrencyStamp], [r].[Name], [r].[NormalizedName]
> FROM [AspNetRoles] AS [r]
> WHERE [r].[NormalizedName] = @__normalizedName_0
> , 
> shaper: UnbufferedEntityShaper<IdentityRole>
> )
> , 
> cancellationToken: queryContext.CancellationToken
> )
> )
> 
> 19:05:15
> [Debug] Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection: Opening connection to database 'deleted' on server 'deleted'.
> 19:05:31
> [Error] Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory: An exception occurred in the database while iterating the results of a query. System.Data.SqlClient.SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct an
> [Error] Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory: An exception occurred in the database while iterating the results of a query.
> System.Data.SqlClient.SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.AggregateException: One or more errors occurred. (Operation is not supported on this platform.) ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
> at System.Runtime.InteropServices.OSPlatform.get_Windows()
> at System.Data.SqlClient.SNI.SNITCPHandle.<ConnectAsync>d__22.MoveNext()
> --- End of inner exception stack trace ---

So far I don't have any ideas why second project doesn't work. The only difference I see is that in second project result type is "IAsyncEnumerable" in opposite to "IEnumerable" return type in first project. 

The same code works fine locally and on cloud foundry. 
I use "0.10.1-preview1" version of "Amazon.Lambda.AspNetCoreServer".

**Comment by strofimo** [comment]
Sorry for false alarm, The problem was in one of dependency which pull .net core 1.1 runtime. After downgrading all works fine now.
