### ISSUE TITLE
Amazon.Lambda.Serialization.Json deserialization error SQS lambda when specifying batch window + at least one message attribute

### ISSUE THREAD

**Issue by wr-cdargis** [aws/aws-lambda-dotnet#1339]
### Describe the bug

Pretty much the title. I have an SQS triggered lambda that works fine if I specify a batch window or add a message attribute. But if I do both of them together the lambda fails.

Here is my lambda custom runtime code

```
class Program
{
    public static async Task Main(string[] args)
    {
        using (HandlerWrapper handlerWrapper = HandlerWrapper.GetHandlerWrapper<SQSEvent, SQSBatchResponse>(HandleAsync, new JsonSerializer()))
        using (LambdaBootstrap bootstrap = new LambdaBootstrap(handlerWrapper))
        {
            await bootstrap.RunAsync();
        }
    }

    private static Task<SQSBatchResponse> HandleAsync(SQSEvent @event, ILambdaContext lambdaContext)
    {
        foreach (SQSEvent.SQSMessage message in @event.Records)
        {
            Console.WriteLine($"Message body: {message.Body}");
        }
        return Task.FromResult(new SQSBatchResponse(new List<SQSBatchResponse.BatchItemFailure>()));
    }
}
```

### Expected Behavior

I expect to be able to specify message attributes and a batching window together. Our application requires that we use the message attributes and now we would like to start raising the batch size significantly.

### Current Behavior

I obtained this error from cloudwatch logs after I created my own `ILambdaSerializer` (just a middle man that called into a `new Amazon.Lambda.Serialization.Json.JsonSerializer()`)

Error:
```
<html>
<body>
<!--StartFragment-->

Amazon.Lambda.Serialization.Json.JsonSerializerException: Error converting the Lambda event JSON payload to type Amazon.Lambda.SQSEvents.SQSEvent: Value cannot be null. (Parameter 's')
--
---> System.ArgumentNullException: Value cannot be null. (Parameter 's')
at System.Convert.FromBase64String(String s)
at Amazon.Lambda.Serialization.Json.Common.Base64ToMemoryStream(String dataBase64)
at Amazon.Lambda.Serialization.Json.JsonToMemoryStreamDataConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
at Amazon.Lambda.Serialization.Json.JsonSerializer.Deserialize[T](Stream requestStream)
--- End of inner exception stack trace ---
at Amazon.Lambda.Serialization.Json.JsonSerializer.Deserialize[T](Stream requestStream)
at Amazon.Lambda.RuntimeSupport.HandlerWrapper.<>c__DisplayClass26_0`2.<<GetHandlerWrapper>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.InvokeOnceAsync(CancellationToken cancellationToken)

<!--EndFragment-->
</body>
</html>
```

### Reproduction Steps

1) Create custom runtime lambda with above code (not sure if this problem is unique to custom runtime)
2) Create SQS queue
3) Hook up trigger from queue -> lambda function. Make sure to specify batch window.
4) Drop a message to the queue that includes at least one message attribute as a string

### Possible Solution

So far I have had two ideas for a workaround. The first is to ignore null values:

```
using (HandlerWrapper handlerWrapper = HandlerWrapper.GetHandlerWrapper<SQSEvent, SQSBatchResponse>(HandleAsync,
    new Amazon.Lambda.Serialization.Json.JsonSerializer((settings) =>
{
    settings.NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore;
})));

```

The second idea would be a man in the middle fix. Something like this:

```
public class MiddleMan : ILambdaSerializer
{
    private readonly Amazon.Lambda.Serialization.Json.JsonSerializer _instance;

    public MiddleMan()
    {
        _instance = new Amazon.Lambda.Serialization.Json.JsonSerializer();
    }

    public T Deserialize<T>(Stream requestStream)
    {
        StreamReader reader = new StreamReader(requestStream);
        string text = reader.ReadToEnd();
        
        // Fix JSON payload.
        Stream fixed = FixJsonPayload(text);
        T t = _instance.Deserialize<T>(fixed );
        return t;
    }

    public void Serialize<T>(T response, Stream responseStream)
    {
        _instance.Serialize(response, responseStream);
    }
}
```

Not sure if one is advised over the other or if there is something better.

### Additional Information/Context

I was able to find the problem with the payloads. When a batch window is not specified the incoming payload looks like this:

```
// entire payload omitted for brevity
"messageAttributes": {
    "stuff": {
        "stringValue": "things",
        "stringListValues": [],
        "binaryListValues": [],
        "dataType": "String"
    }
},
```

When a batch window is specified the payload comes over like this:

```
"messageAttributes": {
    "stuff": {
        "stringValue": "things",
        "binaryValue": null,
        "stringListValues": [],
        "binaryListValues": [],
        "dataType": "String"
    }
},
```

### AWS .NET SDK and/or Package version used

<PackageReference Include="Amazon.Lambda.RuntimeSupport" Version="1.8.2" />
<PackageReference Include="Amazon.Lambda.Serialization.Json" Version="2.1.0" />
<PackageReference Include="Amazon.Lambda.SQSEvents" Version="2.1.0" />

### Targeted .NET Platform

.NET Core 3.1

### Operating System and version

Custom Runtime

**Comment by ashishdhingra** [comment]
Not reproducible in .NET 6 runtime.
- Used below code:
```C#
using Amazon.Lambda.Core;
using Amazon.Lambda.SQSEvents;


// Assembly attribute to enable the Lambda function's JSON input to be converted into a .NET class.
[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer))]

namespace AWSLambda6;

public class Function
{
    /// <summary>
    /// Default constructor. This constructor is used by Lambda to construct the instance. When invoked in a Lambda environment
    /// the AWS credentials will come from the IAM role associated with the function and the AWS region will be set to the
    /// region the Lambda function is executed in.
    /// </summary>
    public Function()
    {

    }


    /// <summary>
    /// This method is called for every Lambda invocation. This method takes in an SQS event object and can be used 
    /// to respond to SQS messages.
    /// </summary>
    /// <param name="evnt"></param>
    /// <param name="context"></param>
    /// <returns></returns>
    public Task<SQSBatchResponse> FunctionHandler(SQSEvent evnt, ILambdaContext context)
    {
        foreach(var message in evnt.Records)
        {
            context.Logger.LogInformation($"Processed message {message.Body}");
            context.Logger.LogInformation($"Message Attributes count: {message.Attributes?.Count};");
            if (message.MessageAttributes != null)
            {
                foreach (var attribute in message.MessageAttributes)
                {
                    context.Logger.LogInformation($"\t{attribute.Key}: {attribute.Value.StringValue}");
                }
            }
        }

        return Task.FromResult(new SQSBatchResponse(new List<SQSBatchResponse.BatchItemFailure>()));
    }
}
```
- Published the Lambda function. Also attached policy `AWSLambdaSQSQueueExecutionRole` to Lambda IAM role.
- In AWS SQS Console, attached Lambda function in Lambda Triggers.
- In AWS Lambda console, changed batch window to `2`.
- From AWS SQS Console, sent the message with message body and 2 message attributes. 
- Below is the output in CloudWatch logs.
```
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|   timestamp   |                                                                                 message                                                                                  |
|---------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1666308995043 | START RequestId: c987479c-1dcd-5d61-a510-1c57c06a7308 Version: $LATEST                                                                                                   |
| 1666308995392 | 2022-10-20T23:36:35.333Z c987479c-1dcd-5d61-a510-1c57c06a7308 info Processed message Test Message                                                                        |
| 1666308995411 | 2022-10-20T23:36:35.411Z c987479c-1dcd-5d61-a510-1c57c06a7308 info Message Attributes count: 4;                                                                          |
| 1666308995412 | 2022-10-20T23:36:35.412Z c987479c-1dcd-5d61-a510-1c57c06a7308 info  testattribute2: testattributevalue2                                                                  |
| 1666308995412 | 2022-10-20T23:36:35.412Z c987479c-1dcd-5d61-a510-1c57c06a7308 info  testattribute1: testattributevalue1                                                                  |
| 1666308995510 | END RequestId: c987479c-1dcd-5d61-a510-1c57c06a7308                                                                                                                      |
| 1666308995510 | REPORT RequestId: c987479c-1dcd-5d61-a510-1c57c06a7308 Duration: 467.70 ms Billed Duration: 468 ms Memory Size: 256 MB Max Memory Used: 61 MB Init Duration: 213.22 ms   |
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**TODO:** Need to reproduce with custom runtime.

**Comment by wr-cdargis** [comment]
@ashishdhingra I should have been more explicit with my code example. I'm using `Amazon.Lambda.Serialization.Json.JsonSerializer`. i.e.

```
public static async Task Main(string[] args)
{
    using (HandlerWrapper handlerWrapper = HandlerWrapper.GetHandlerWrapper<SQSEvent, SQSBatchResponse>(HandleAsync, new Amazon.Lambda.Serialization.Json.JsonSerializer()))
    using (LambdaBootstrap bootstrap = new LambdaBootstrap(handlerWrapper))
    {
        await bootstrap.RunAsync();
    }
}
```

**Comment by ashishdhingra** [comment]
Reproducible when using custom lambda runtime (`.NET Core 3.1`) and `Amazon.Lambda.Serialization.Json.JsonSerializer`. The blueprint template for custom runtime targeting `.NET Core 3.1` is available in `Amazon.Lambda.Templates::4.1.2`.
- **.csproj**
```XML
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AWSProjectType>Lambda</AWSProjectType>
    <AssemblyName>bootstrap</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.RuntimeSupport" Version="1.8.2" />
    <PackageReference Include="Amazon.Lambda.Core" Version="2.1.0" />
    <PackageReference Include="Amazon.Lambda.SQSEvents" Version="2.1.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="2.1.0" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Amazon.Lambda.SQSEvents" />
    <None Remove="Amazon.Lambda.Serialization.Json" />
  </ItemGroup>
</Project>
```
- **Function.cs**
```C#
using Amazon.Lambda.Core;
using Amazon.Lambda.RuntimeSupport;
using Amazon.Lambda.Serialization.Json;
using Amazon.Lambda.SQSEvents;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace CustomRuntimeSQSTest
{
    public class Function
    {
        /// <summary>
        /// The main entry point for the custom runtime.
        /// </summary>
        /// <param name="args"></param>
        private static async Task Main(string[] args)
        {
            Func<SQSEvent, ILambdaContext, SQSBatchResponse> func = FunctionHandler;
            using(var handlerWrapper = HandlerWrapper.GetHandlerWrapper<SQSEvent, SQSBatchResponse>(func, new JsonSerializer()))
            using(var bootstrap = new LambdaBootstrap(handlerWrapper))
            {
                await bootstrap.RunAsync();
            }
        }

        /// <summary>
        /// This method is called for every Lambda invocation. This method takes in an SQS event object and can be used 
        /// to respond to SQS messages.
        /// </summary>
        /// <param name="evnt"></param>
        /// <param name="context"></param>
        /// <returns></returns>
        public static SQSBatchResponse FunctionHandler(SQSEvent evnt, ILambdaContext context)
        {
            foreach (var message in evnt.Records)
            {
                context.Logger.LogLine($"Processed message {message.Body}");
                context.Logger.LogLine($"Message Attributes count: {message.Attributes?.Count};");
                if (message.MessageAttributes != null)
                {
                    foreach (var attribute in message.MessageAttributes)
                    {
                        context.Logger.LogLine($"\t{attribute.Key}: {attribute.Value.StringValue}");
                    }
                }
            }

            return new SQSBatchResponse(new List<SQSBatchResponse.BatchItemFailure>());
        }
    }
}
```
- **aws-lambda-tools-defaults.json**
```JSON
{
  "Information": [
    "This file provides default values for the deployment wizard inside Visual Studio and the AWS Lambda commands added to the .NET Core CLI.",
    "To learn more about the Lambda commands with the .NET Core CLI execute the following command at the command line in the project root directory.",
    "dotnet lambda help",
    "All the command line options for the Lambda command can be specified in this file."
  ],
  "profile": "",
  "region": "",
  "configuration": "Release",
  "framework": "netcoreapp3.1",
  "function-runtime": "provided",
  "function-memory-size": 256,
  "function-timeout": 30,
  "function-handler": "not_required_for_custom_runtime",
  "msbuild-parameters": "--self-contained true"
}
```

Configuring Lambda trigger with batch window (tested with value `1`) and sending message generates below in CloudWatch logs:
```
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|   timestamp   |                                                                                                                             message                                                                                                                             |
|---------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1666392485712 | START RequestId: 5ef83ad0-9cf3-561f-949b-611dbf4d3c0f Version: $LATEST                                                                                                                                                                                          |
| 1666392487746 | Amazon.Lambda.Serialization.Json.JsonSerializerException: Error converting the Lambda event JSON payload to type Amazon.Lambda.SQSEvents.SQSEvent: Value cannot be null. (Parameter 's')                                                                        |
| 1666392487746 | ---> System.ArgumentNullException: Value cannot be null. (Parameter 's')                                                                                                                                                                                        |
| 1666392487746 | at System.Convert.FromBase64String(String s)                                                                                                                                                                                                                    |
| 1666392487746 | at Amazon.Lambda.Serialization.Json.Common.Base64ToMemoryStream(String dataBase64)                                                                                                                                                                              |
| 1666392487746 | at Amazon.Lambda.Serialization.Json.JsonToMemoryStreamDataConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)                                                                                               |
| 1666392487746 | at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)                                                                                         |
| 1666392487746 | at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)               |
| 1666392487746 | at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)                                                                                  |
| 1666392487746 | at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)         |
| 1666392487746 | at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)  |
| 1666392487746 | at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)                                                         |
| 1666392487746 | at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)         |
| 1666392487746 | at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)  |
| 1666392487746 | at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)               |
| 1666392487746 | at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)                                                                                  |
| 1666392487746 | at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)         |
| 1666392487746 | at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)  |
| 1666392487746 | at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)                                                                                |
| 1666392487746 | at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)                                                                       |
| 1666392487746 | at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)  |
| 1666392487746 | at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)               |
| 1666392487746 | at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)                                                                                  |
| 1666392487746 | at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)         |
| 1666392487746 | at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)  |
| 1666392487746 | at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)                                                                                                                   |
| 1666392487746 | at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)                                                                                                                                                                       |
| 1666392487746 | at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)                                                                                                                                                                               |
| 1666392487746 | at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)                                                                                                                                                                                             |
| 1666392487746 | at Amazon.Lambda.Serialization.Json.JsonSerializer.Deserialize[T](Stream requestStream)                                                                                                                                                                         |
| 1666392487746 | --- End of inner exception stack trace ---                                                                                                                                                                                                                      |
| 1666392487746 | at Amazon.Lambda.Serialization.Json.JsonSerializer.Deserialize[T](Stream requestStream)                                                                                                                                                                         |
| 1666392487746 | at Amazon.Lambda.RuntimeSupport.HandlerWrapper.<>c__DisplayClass44_0`2.<GetHandlerWrapper>b__0(InvocationRequest invocation)                                                                                                                                    |
| 1666392487746 | at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.InvokeOnceAsync(CancellationToken cancellationToken)                                                                                                                                                            |
| 1666392488507 | END RequestId: 5ef83ad0-9cf3-561f-949b-611dbf4d3c0f                                                                                                                                                                                                             |
| 1666392488507 | REPORT RequestId: 5ef83ad0-9cf3-561f-949b-611dbf4d3c0f Duration: 2794.91 ms Billed Duration: 3250 ms Memory Size: 256 MB Max Memory Used: 89 MB Init Duration: 454.58 ms                                                                                        |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

Changing batch window to default `0` (which is `None`) successfully executes Lambda function when message is sent. Below is logged in CloudWatch logs:
```
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|   timestamp   |                                                                                  message                                                                                   |
|---------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1666393036229 | START RequestId: a1636524-dd06-57ea-9231-3ee9fb014c04 Version: $LATEST                                                                                                     |
| 1666393037897 | Processed message Test Message Custom runtime                                                                                                                              |
| 1666393037897 | Message Attributes count: 4;                                                                                                                                               |
| 1666393037897 | testattr2: testval2                                                                                                                                                        |
| 1666393037897 | testattr1: testval1                                                                                                                                                        |
| 1666393038316 | END RequestId: a1636524-dd06-57ea-9231-3ee9fb014c04                                                                                                                        |
| 1666393038316 | REPORT RequestId: a1636524-dd06-57ea-9231-3ee9fb014c04 Duration: 2086.83 ms Billed Duration: 2528 ms Memory Size: 256 MB Max Memory Used: 82 MB Init Duration: 440.96 ms   |
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by wr-cdargis** [comment]
I would expect this to be reproducible in .NET 6 if `Amazon.Lambda.Serialization.Json.JsonSerializer` was used there

**Comment by mseld** [comment]
I hope this might fix deserialization sqs event problem  

Reference: https://aws.amazon.com/blogs/compute/building-serverless-net-applications-on-aws-lambda-using-net-7/ 

```
/// <summary>
/// This class is used to register the input event and return type for the FunctionHandler method with the System.Text.Json source generator.
/// There must be a JsonSerializable attribute for each type used as the input and return type or a runtime error will occur
/// from the JSON serializer unable to find the serialziation information for unknown types.
/// </summary>
[JsonSerializable(typeof(SQSBatchResponse))]
[JsonSerializable(typeof(SQSEvent))]
public partial class LambdaFunctionJsonSerializerContext : JsonSerializerContext
{
    // By using this partial class derived from JsonSerializerContext, we can generate reflection free JSON Serializer code at compile time
    // which can deserialize our class and properties. However, we must attribute this class to tell it what types to generate serialization code for.
    // See https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-source-generation
}
```

**Comment by kakins** [comment]
> [JsonSerializable(typeof(SQSBatchResponse))]
> [JsonSerializable(typeof(SQSEvent))]
> public partial class LambdaFunctionJsonSerializerContext : JsonSerializerContext
> {
>     // By using this partial class derived from JsonSerializerContext, we can generate reflection free JSON Serializer code at compile time
>     // which can deserialize our class and properties. However, we must attribute this class to tell it what types to generate serialization code for.
>     // See https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-source-generation
> }

This doesn't appear to be working in the .NET 6 runtime.  I think I've followed all the instructions so far for SQS.  Serialization doesn't appear to be working for the SQSEvent

![image](https://user-images.githubusercontent.com/14915247/215212899-149385f5-051b-40fb-8423-63def3245fb3.png)

**Comment by ashishdhingra** [comment]
@wr-cdargis The issue has been fixed in [Amazon.Lambda.Serialization.Json version 2.1.1](https://www.nuget.org/packages/Amazon.Lambda.Serialization.Json/2.1.1). Please update this package to latest version and confirm if it works for you.

Thanks,
Ashish
