### ISSUE TITLE
Test Tool 7.0 requires deps.json

### ISSUE THREAD

**Issue by fiannafritz** [aws/aws-lambda-dotnet#1411]
### Describe the bug

I'm trying to run dotnet-lambda-test-tool-7.0 and getting the following error.

`Unknown error occurred causing process exit: Failed to find a deps.json file in the specified directory (C:\Users\kroan\documents\Test)
   at Amazon.Lambda.TestTool.Runtime.LocalLambdaRuntime.Initialize(String directory, IAWSService awsService) in C:\build\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool\Runtime\LocalLambdaRuntime.cs:line 59
   at Amazon.Lambda.TestTool.Runtime.LocalLambdaRuntime.Initialize(String directory) in C:\build\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool\Runtime\LocalLambdaRuntime.cs:line 46
   at Amazon.Lambda.TestTool.TestToolStartup.Startup(String productName, Action`2 uiStartup, String[] args, RunConfiguration runConfiguration) in C:\build\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool\TestToolStartup.cs:line 81`

### Expected Behavior

The project runs and opens the Mock Lambda Test Tool

### Current Behavior

Error occurs asking for deps.json

### Reproduction Steps

Install the 7.0 test tool. Open PowerShell and run dotnet-lambda-test-tool-7.0

### AWS .NET SDK and/or Package version used

dotnet-lambda-test-tool-7.0

### Targeted .NET Platform

.NET 7

### Operating System and version

Windows 10

**Comment by fiannafritz** [comment]
I got it working. I didn't understand where the tool needed to be run from.
