### ISSUE TITLE
`dotnet lambda package` in WSL (Ubuntu on Windows) using windows `dotnet publish`

### ISSUE THREAD

**Issue by simonbuchan** [aws/aws-lambda-dotnet#150]
`dotnet lambda package` is failing for me on lambda tools from at least 1.6 when I run it from WSL, while `dotnet publish` works. It seems like it is trying to use the windows `dotnet.exe`, rather than the WSL ubuntu `dotnet`. I am using the dotnet core 2.0 SDK, but I have the 1.0 shared framework installed.

Setting up a trivial project:

```
➜ dotnet new console -o lambda-publish
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on lambda-publish/lambda-publish.csproj...
  Restoring packages for /mnt/c/code/tests/lambda-publish/lambda-publish.csproj...
  Generating MSBuild file /mnt/c/code/tests/lambda-publish/obj/lambda-publish.csproj.nuget.g.props.
  Generating MSBuild file /mnt/c/code/tests/lambda-publish/obj/lambda-publish.csproj.nuget.g.targets.
  Restore completed in 200.31 ms for /mnt/c/code/tests/lambda-publish/lambda-publish.csproj.


Restore succeeded.

➜ cd lambda-publish
➜ vim lambda-publish.csproj
➜ cat lambda-publish.csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Amazon.Lambda.Tools" Version="1.6.0" />
  </ItemGroup>

</Project>
➜ dotnet restore
  Restoring packages for /mnt/c/code/tests/lambda-publish/lambda-publish.csproj...
  Restore completed in 20.04 ms for /mnt/c/code/tests/lambda-publish/lambda-publish.csproj.
  Restore completed in 2.67 sec for /mnt/c/code/tests/lambda-publish/lambda-publish.csproj.
```

From here `dotnet publish` works fine:

```
➜ dotnet publish -c Release -f netcoreapp1.0
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  lambda-publish -> /mnt/c/code/tests/lambda-publish/bin/Release/netcoreapp1.0/lambda-publish.dll
  lambda-publish -> /mnt/c/code/tests/lambda-publish/bin/Release/netcoreapp1.0/publish/
````

But `dotnet lambda package` blows up, trying to use the old windows dotnet 1.1 SDK that came with VS or something, which doesn't have the 1.0 shared framework:

```
➜ dotnet lambda package -c Release -f netcoreapp1.0
Executing publish command
... invoking 'dotnet publish', working folder '/mnt/c/code/tests/lambda-publish/bin/Release/netcoreapp1.0/publish'
... publish: Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
... publish: Copyright (C) Microsoft Corporation. All rights reserved.
... publish: C:\Program Files\dotnet\sdk\1.1.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(308,5): error : Assets file '/mnt/c/code/tests/lambda-publish/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [C:\code\tests\lambda-publish\lambda-publish.csproj]
... publish: C:\Program Files\dotnet\sdk\1.1.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(157,5): error : Assets file '/mnt/c/code/tests/lambda-publish/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [C:\code\tests\lambda-publish\lambda-publish.csproj]
... publish: C:\Users\simon\AppData\Local\Temp\.NETCoreApp,Version=v1.0.AssemblyAttributes.cs(4,20): error CS0400: The type or namespace name 'System' could not be found in the global namespace (are you missing an assembly reference?) [C:\code\tests\lambda-publish\lambda-publish.csproj]
... publish: obj\Release\netcoreapp1.0\lambda-publish.AssemblyInfo.cs(10,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [C:\code\tests\lambda-publish\lambda-publish.csproj]
<snip>
... publish: Program.cs(7,16): error CS0518: Predefined type 'System.Void' is not defined or imported [C:\code\tests\lambda-publish\lambda-publish.csproj]
... publish: C:\Program Files\dotnet\sdk\1.1.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(92,5): error : Assets file '/mnt/c/code/tests/lambda-publish/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [C:\code\tests\lambda-publish\lambda-publish.csproj]
Failed to create application package
```

Probably related issue, when run without parameters `dotnet lambda package` on 1.6.0 gives the same error after prompting for configuration and framework, but bumping to 1.7.0 gives:

```
➜ dotnet lambda package
Unknown error executing Lambda packaging: Value cannot be null.
Parameter name: paths
   at System.IO.Path.Combine(String[] paths)
   at Amazon.Lambda.Tools.LambdaPackager.CreateApplicationBundle(LambdaToolsDefaults defaults, IToolLogger logger, String workingDirectory, String projectLocation, String configuration, String targetFramework, String& publishLocation, String& zipArchivePath)
   at Amazon.Lambda.Tools.Commands.PackageCommand.<ExecuteAsync>b__22_0()
```

**Comment by simonbuchan** [comment]
Bug is https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.Tools/DotNetCLIWrapper.cs#L50

Here is how the asp.net core tools do it: https://github.com/aspnet/DotNetTools/blob/6f1057a7603d3ece343d265e484517ef950ada4f/shared/DotNetMuxer.cs

**Comment by simonbuchan** [comment]
Workaround for now: `PATH=/usr/bin:/bin dotnet lambda package -c Release -f netcoreapp1.0`, which removes `dotnet.exe` from the path.

**Comment by normj** [comment]
Yeap, that is a case we didn't take into account of having both dotnet.exe and dotnet in the path at the same time.

**Comment by simonbuchan** [comment]
The parameterless 1.7.0 null path error repros in CMD, so I'll open it as a separate issue.

**Comment by normj** [comment]
I pushed out version 1.7.1 which incorporate some of the logic from DotNetMuxer to improve searching for the dotnet CLI.

**Comment by simonbuchan** [comment]
Works great, thanks!
