### ISSUE TITLE
Lambda Test Tool returns Error deserializing the input JSON to type APIGatewayProxyRequest with System.Text.Json v7

### ISSUE THREAD

**Issue by max-maksimov** [aws/aws-lambda-dotnet#1516]
Hi,
I'm working with solution on .net6 with lambda project, and AWS Toolkit for Visual Studio.
I faced with issue testing lambda locally using Lambda Test Tool.
In case if solution has a reference to `System.Text.Json` version 7 and above. 
When I Execute Function from Mock Lambda Test Tool I get following error: "_Error deserializing the input JSON to type APIGatewayProxyRequest_", see full error log below, interesting part goes under the **Inner 2 Exception**: "_Operation is not supported on this platform_".

```
System.Exception: Error deserializing the input JSON to type APIGatewayProxyRequest
   at Amazon.Lambda.TestTool.Runtime.LambdaExecutor.BuildParameters(ExecutionRequest request, ILambdaContext context) in C:\build\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool\Runtime\LambdaExecutor.cs:line 255
   at Amazon.Lambda.TestTool.Runtime.LambdaExecutor.ExecuteAsync(ExecutionRequest request) in C:\build\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool\Runtime\LambdaExecutor.cs:line 65

---------------- Inner 1 Exception ------------

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Amazon.Lambda.TestTool.Runtime.LambdaExecutor.BuildParameters(ExecutionRequest request, ILambdaContext context) in C:\build\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool\Runtime\LambdaExecutor.cs:line 225

---------------- Inner 2 Exception ------------

Amazon.Lambda.Serialization.SystemTextJson.JsonSerializerException: Error converting the Lambda event JSON payload to type Amazon.Lambda.APIGatewayEvents.APIGatewayProxyRequest: Operation is not supported on this platform.
   at Amazon.Lambda.Serialization.SystemTextJson.AbstractLambdaJsonSerializer.Deserialize[T](Stream requestStream)

---------------- Inner 3 Exception ------------

System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Text.Encodings.Web.OptimizedInboxTextEncoder.AllowedAsciiCodePoints.get_AsVector()
   at System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstByteToEncodeSsse3(Byte* pData, UIntPtr lengthInBytes)
   at System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstByteToEncode(ReadOnlySpan`1 data)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo.CacheNameAsUtf8BytesAndEscapedNameSection()
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo.Configure()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.InitializePropertyCache()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureLocked|143_0()
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Boolean resolveIfMutable)
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 utf8Json, JsonSerializerOptions options)
   at Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer.InternalDeserialize[T](Byte[] utf8Json)
   at Amazon.Lambda.Serialization.SystemTextJson.AbstractLambdaJsonSerializer.Deserialize[T](Stream requestStream)
``` 
Once I downgraded `System.Text.Json` package to version 6 in my solution, I'm able to invoke lambda from Lambda Test Tool.
Moreover with `System.Text.Json` package version 7 I was able to invoke my function from AWS Console, meaning it does able to deserialize input to APIGatewayProxyRequest, so the issue seems to be in Mock Lambda Test Tool itself.

### Expected Behavior

`System.Text.Json` version 7+ should not cause deserializing errors using AWS .NET Core 6.0 Mock Lambda Test Tool

### Current Behavior

`System.Text.Json` version 7+ causes deserializing errors using AWS .NET Core 6.0 Mock Lambda Test Tool

### Reproduction Steps

You can use any Lambda .net6 project, include `System.Text.Json` v7+ package in project.
Also add AWS Toolkit for Visual Studio (if using that IDE)
Test your lambda with Mock Lambda Test Tool
Execute Function from Mock Lambda Test Tool, see deserializing error in response.

### AWS .NET SDK and/or Package version used

Packages in solution:
- `Amazon.Lambda.Core` v2.1.0 
- `Amazon.Lambda.Serialization.SystemTextJson` v2.3.1
- `Amazon.Lambda.APIGatewayEvents` v2.6.0
- `System.Text.Json` v7.0.2

### Targeted .NET Platform

.NET 6

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
Hi @max-maksimov,

Good morning.

Thanks for reporting the issue. I created Lambda project using the Empty Lambda function VS template and added the above required packages. However, I'm unable to get the `System.Text.Json v7` assembly to load. Could you please share the following:
- Version of Lambda Test Tool used
- Version of AWS Toolkit for Visual Studio installed
- Sample code solution for reproduction (you may zip your code solution and share it here)

Thanks,
Ashish

**Comment by max-maksimov** [comment]
Hi @ashishdhingra,
Thanks for looking into it. 

I've got following versions installed:
- Lambda Test Tool v0.13.0
- AWS Toolkit for Visual Studio v1.39.0.0
Sorry, but I cannot share my project. 
Tried to reproduce an issue on my end again by updating, `System.Text.Json` to v7. I also see both versions (v7 and v6) of `System.Text.Json` are loaded, and issue is reproducible for me.

Thanks.

**Comment by max-maksimov** [comment]
Hi @ashishdhingra,

I've attached a lambda solution example in which I'm able to reproduce the issue.
Please take a look.

[lambdatest_service.zip](https://github.com/aws/aws-lambda-dotnet/files/11636772/lambdatest_service.zip)

Thanks!

**Comment by ashishdhingra** [comment]
> ```
> CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
>     
>     <PublishReadyToRun>true</PublishReadyToRun>
> ```

Reproducible using customer's solution. However, adding `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` in `.csproj` file resolves the issue.

**Comment by normj** [comment]
Good catch @ashishdhingra! Our Lambda .NET blueprints all have `CopyLocalLockFileAssemblies` set to true in the project file and  is highly recommended whenever using the test tool.

**Comment by ashishdhingra** [comment]
> Good catch @ashishdhingra! Our Lambda .NET blueprints all have `CopyLocalLockFileAssemblies` set to true in the project file and is highly recommended whenever using the test tool.

@max-maksimov Please try adding `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` in your `.csproj` file.

**Comment by max-maksimov** [comment]
@ashishdhingra,
Adding `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` property in project file solved the issue.

Thanks!

**Comment by ashishdhingra** [comment]
@max-maksimov Thanks for the confirmation.
