### ISSUE TITLE
Documented handler max length of 128 characters isn't supported

### ISSUE THREAD

**Issue by SeijiSuenaga** [aws/aws-lambda-dotnet#1642]
### Describe the bug

AWS documentation says the `Handler` property has a [max length 128 characters](https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#SSS-CreateFunction-request-Handler), but values exactly 128 characters long appear to be truncated to 127 characters in the `dotnet6` Lambda runtime, and therefore fail.

### Expected Behavior

A handler value exactly 128 characters long shouldn't be truncated and should invoke the handler method successfully.

### Current Behavior

A handler value exactly 128 characters long produces a failure:

```log
Amazon.Lambda.RuntimeSupport.ExceptionHandling.LambdaValidationException: Unable to find method 'HandleInvocationAsyn' in type 'An.Example.Namespace.For.The.GitHub.Issue.ExampleLambdaFunction' from assembly 'An.Example.Namespace.For.The.GitHub.Issue': Found no methods matching method name 'HandleInvocationAsyn'.
   at Amazon.Lambda.RuntimeSupport.Bootstrap.UserCodeLoader.FindCustomerMethod(Type type) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/UserCodeLoader.cs:line 242
   at Amazon.Lambda.RuntimeSupport.Bootstrap.UserCodeLoader.Init(Action`1 customerLoggingAction) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/UserCodeLoader.cs:line 116
   at Amazon.Lambda.RuntimeSupport.Bootstrap.UserCodeInitializer.InitializeAsync() in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/UserCodeInitializer.cs:line 46
   at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.InitializeAsync() in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/LambdaBootstrap.cs:line 155
```

### Reproduction Steps

Create a Lambda with a handler specification that is exactly 128 characters long, such as:

`An.Example.Namespace.For.The.GitHub.Issue::An.Example.Namespace.For.The.GitHub.Issue.ExampleLambdaFunction.HandleInvocationAsync`

### Additional Information/Context

AWS Console shows the full value in the "Runtime settings" of the Lambda function, so it seems to be getting truncated somewhere in the Lambda runtime.

### AWS .NET SDK and/or Package version used

N/A — this bug is independent from .NET SDK.

### Targeted .NET Platform

.NET 6

### Operating System and version

Amazon Linux 2

**Comment by ashishdhingra** [comment]
@SeijiSuenaga Good morning. Thanks for opening the issue. Kindly refer [Lambda function handler in C#](https://docs.aws.amazon.com/lambda/latest/dg/csharp-handler.html); if you scroll down a little, there is an example for format of function handler `GetProductHandler::GetProductHandler.Function::FunctionHandler`. This is in the format `ASSEMBLY::TYPE::METHOD`. So in `aws-lambda-tools.defaults.json`, the value for `function-handler` for your use case would have been `An.Example.Namespace.For.The.GitHub.Issue::An.Example.Namespace.For.The.GitHub.Issue.ExampleLambdaFunction::HandleInvocationAsync` (not `An.Example.Namespace.For.The.GitHub.Issue::An.Example.Namespace.For.The.GitHub.Issue.ExampleLambdaFunction.HandleInvocationAsync`, this is a wrong specification). This handler name is `129` characters long, and hence, the last letter is truncated by runtime (not in Lambda function settings) due to limit of `128` characters.

If you deploy this function via Visual Studio (using latest AWS Toolkit), it will throw validation error during deployment.

Could you check the function handler name in above format in your Lambda function settings?

Thanks,
Ashish

**Comment by SeijiSuenaga** [comment]
@ashishdhingra Ah I'm sorry, I got that example wrong 😓 but my actual Lambda function settings have the correct format you specified.  Here's the actual format I'm using, with my company's namespace hidden:

`XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX::XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.LambdaFunction::HandleAsync`

And the resulting error:

> Amazon.Lambda.RuntimeSupport.ExceptionHandling.LambdaValidationException: Unable to find method 'HandleAsyn' in type 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.LambdaFunction' from assembly 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX': Found no methods matching method name 'HandleAsyn'.

I'll edit the OP to correct the example.

**Comment by ashishdhingra** [comment]
Appears to be reproducible using below code:
```C#
using Amazon.Lambda.Core;

// Assembly attribute to enable the Lambda function's JSON input to be converted into a .NET class.
[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer))]

namespace XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX;

public class LambdaFunction
{
    public async Task<string> HandleAsync(string input, ILambdaContext context)
    {
        return await Task.Run<string>(() => { return input.ToUpper(); });
    }
}
```
**aws-lambda-tools-defaults.json**
```JSON
{
    "Information" : [
        "This file provides default values for the deployment wizard inside Visual Studio and the AWS Lambda commands added to the .NET Core CLI.",
        "To learn more about the Lambda commands with the .NET Core CLI execute the following command at the command line in the project root directory.",
        "dotnet lambda help",
        "All the command line options for the Lambda command can be specified in this file."
    ],
    "profile"     : "default",
    "region"      : "us-east-2",
    "configuration" : "Release",
    "function-architecture" : "x86_64",
    "function-runtime"      : "dotnet6",
    "function-memory-size"  : 256,
    "function-timeout"      : 30,
    "function-handler"      : "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX::XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.LambdaFunction::HandleAsync",
    "framework"             : "net6.0",
    "function-name"         : "TestFunction",
    "package-type"          : "Zip",
    "function-role"         : "arn:aws:iam::139480602983:role/lambda_exec_TestFunction",
    "function-subnets"      : "",
    "function-security-groups" : "",
    "tracing-mode"             : "PassThrough",
    "environment-variables"    : "",
    "image-tag"                : ""
}
```
The handler name is `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX::XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.LambdaFunction::HandleAsync` is 128 characters long. The Lambda function configuration is also correct. However, when executing Lambda code via AWS console, following exception is logged:
```JSON
{
  "errorType": "LambdaValidationException",
  "errorMessage": "Unable to find method 'HandleAsyn' in type 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.LambdaFunction' from assembly 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX': Found no methods matching method name 'HandleAsyn'.",
  "stackTrace": [
    "at Amazon.Lambda.RuntimeSupport.Bootstrap.UserCodeLoader.FindCustomerMethod(Type type) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/UserCodeLoader.cs:line 242",
    "at Amazon.Lambda.RuntimeSupport.Bootstrap.UserCodeLoader.Init(Action`1 customerLoggingAction) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/UserCodeLoader.cs:line 116",
    "at Amazon.Lambda.RuntimeSupport.Bootstrap.UserCodeInitializer.InitializeAsync() in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/UserCodeInitializer.cs:line 46",
    "at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.InitializeAsync() in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/LambdaBootstrap.cs:line 159"
  ]
}
```
Might be some issue in `Amazon.Lambda.RuntimeSupport` package.

Needs review with the team.

Thanks,
Ashish

**Comment by ashishdhingra** [comment]
P109288213
