### ISSUE TITLE
Unable to finalize SQL Server connection - System.EntryPointNotFoundException thrown for CryptoNative_X509StoreCtxInit2

### ISSUE THREAD

**Issue by Kyefer** [aws/aws-lambda-dotnet#181]
I'm currently in the process of moving an ASP.NET core application into the dotnet lambda runtime using the Amazon.Lambda.AspNetCoreServer package. But during runtime, whenever the connection to the SQL Server is created , it fails during the pre-login encryption handshake. It looks like the lambda environment or the build artifacts doesn't have the proper SSL native binaries. I'm sure that others have been able to open SQL Server connections in lambda so I'm hoping this issue can be resolved by some configuration and/or proper package version usage.

The exception:
```
Unknown error responding to request: SqlException:
System.Data.SqlClient.SqlException: A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: SSL Provider, error: 31 - Encryption(ssl/tls) handshake failed) ---> System.EntryPointNotFoundException: Unable to find an entry point named 'CryptoNative_X509StoreCtxInit2' in DLL 'System.Security.Cryptography.Native'.
at Interop.Crypto.X509StoreCtxInit(SafeX509StoreCtxHandle ctx, SafeX509StoreHandle store, SafeX509Handle x509, SafeX509StackHandle extraCerts)
at Internal.Cryptography.Pal.OpenSslX509ChainProcessor.BuildChain(X509Certificate2 leaf, HashSet`1 candidates, HashSet`1 systemTrusted, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationMode revocationMode, X509RevocationFlag revocationFlag, DateTime verificationTime, TimeSpan& remainingDownloadTime)
at Internal.Cryptography.Pal.ChainPal.BuildChain(Boolean useMachineContext, ICertificatePal cert, X509Certificate2Collection extraStore, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationMode revocationMode, X509RevocationFlag revocationFlag, DateTime verificationTime, TimeSpan timeout)
at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate)
at System.Net.Security.CertificateValidation.BuildChainAndVerifyProperties(X509Chain chain, X509Certificate2 remoteCertificate, Boolean checkCertName, String hostName)
at System.Net.Security.SecureChannel.VerifyRemoteCertificate(RemoteCertValidationCallback remoteCertValidationCallback)
at System.Net.Security.SslState.CompleteHandshake()
at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Data.SqlClient.SNI.SNITCPHandle.EnableSsl(UInt32 options)
at System.Data.SqlClient.SNI.SNIProxy.EnableSsl(SNIHandle handle, UInt32 options)
--- End of inner exception stack trace ---
at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
at System.Data.SqlClient.SqlConnection.Open()
at SPSC.PDS.Data.ConnectionFactory.Create()
at SPSC.PDS.Data.Repository`1..ctor(IConnectionFactory connectionFactory)
```

The project consists of many projects. The one that is being packaged has the following .csproj:
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.0</TargetFramework>
    <PreserveCompilationContext>false</PreserveCompilationContext>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="0.10.2-preview1" />
    <PackageReference Include="Microsoft.AspNetCore" Version="1.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.0.5" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Amazon.Lambda.Tools" Version="1.8.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SPSC.PDS.Domain\SPSC.PDS.Domain.csproj" />
    <ProjectReference Include="..\SPSC.PDS.IoC\SPSC.PDS.IoC.csproj" />
    <ProjectReference Include="..\SPSC.PDS.Model\SPSC.PDS.Model.csproj" />
  </ItemGroup>
</Project>
```

Additionally, the SQL connection lives in the project with the following .csproj. The package `Dapper.FastCrud` includes the SqlClient file, which is version 4.1.0 (I believe higher versions cause some issues)
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper.FastCrud" Version="2.4.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="1.0.2" />
  </ItemGroup>

</Project>
```

**Comment by pawepaw** [comment]
@Kyefer Got the same problem. Did you found a solution?

**Comment by ibuchan72390** [comment]
I experienced this issue a little while back with the MySQL .Data 7.0.7-m61 library (Only MySQL.Data release for .NET Core 1.0).  When I was working in 1.0.4, I had to explicitly pin a dependency to System.Security.Cryptography.x509Certificates to 4.1.0 and then I also had to include a dependency on System.Security.Cryptography.OpenSsl to 4.0.1.  It's explicitly missing a specific native library implementation that's referenced in x509; I included the OpenSsl pin because of the last two postings on the following thread: https://github.com/dotnet/corefx/issues/9171

That seemed to get things up and running for me when I transitioned to 1.0.4.  When I upgraded into .NET Core 1.0.5, then I ran into the issue again and it was oddly fixed by unpinning those exact dependent libraries and upgrading every other dependent library into 1.0.5.

**Comment by HaroonSaid** [comment]
Look thru obj/project.assets.json file in the lambda project.  
Ensure you don't have any .netstandard/1.6.1 and any reference to 4.3.0 System.* dlls.

**Comment by ibuchan72390** [comment]
As long as they're using the "dotnet lambda package" command, that will properly warn them if they're referencing a package outside of the .NET Core 1.0 Framework.  The problem seems to be that Lambda is specifically on .NET Core 1.0.1 (http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html).  While not ALL packages outside of 1.0.1 will cause runtime failures, some of them will.  System.Security.Cryptography.x509Certificates is one of those specific packages from my personal experience.

Since NuGet allows for "greater than" ranges, you may want to go into your csproj file for your final application and explicitly update the reference on System.Security.Cryptography.x509Certicficates to [4.1.0] so that it will explicitly fail to build on any attempts to upgrade that package out of the 4.1.0 version.

**Comment by Kyefer** [comment]
@ibuchan72390 Thank you! Pinning the specific versions of System.Security.Cryptography.x509Certificates and System.Security.Cryptography.OpenSsl and downgrading to 1.0.4 worked. Do you know if 4.1.0 and 4.0.1 are the highest working versions of the pinned packages?

**Comment by ibuchan72390** [comment]
From my experience, yes, that's exactly the issue.   I attempted to upgrade to 1.0.5, but I ended up fighting this exact issue for a couple days.  As long as you allow NuGet to work with the greater than / equal to strategy, it will almost be guaranteed to screw you in the long run if you accidentally update an upstream package unless you explicitly pin these problem packages.

I believe there may be a much larger issue in that referencing any packages outside of .NET Core 1.0.1 is not guaranteed to work.  According to the link I posted above, Lambda supports .NET Core 1.0.1 runtime ONLY at the current moment.  We can be adventurous and attempt to foray into 1.0.2+; however, they can't guarantee us any of these libraries are going to work.  I have seen some people adventure successfully into 1.0.5 in some of these other issues posts; however, I have not had that same experience.  Currently, I'm experimenting with expressly pinning Microsoft.NETCore.App to version [1.0.1] in my final web project to see if I can identify any unintentionally upgraded packages as I believe these may be dangerous in the long run.

**Comment by djaquez** [comment]
I'm sure this issue will go away with .netcore 2.0.  Can't wait for AWS to move Lambda to .netcore 2.0!

**Comment by ibuchan72390** [comment]
If we're all back to compiling and running as expected, I think we can probably close this issue.

Hopefully Lambda 2.0 will be coming soon. I will be very happy the day of its release.

**Comment by normj** [comment]
Closing as suggested

**Comment by mrwcjoughin** [comment]
@ibuchan72390 thank you - i have been strugging for ages to get sql to work in lambda - and your advise on which packages at which versions to use has finally solved it for me!

for others who are just looking for the latest reply this is the final result of packages in my .csproj file that worked (obviously you may have more, but you need these at these versions for it to work):
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="1.0.3" />
    <PackageReference Include="Microsoft.AspNetCore" Version="1.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.0.4" />
    <PackageReference Include="System.Runtime.InteropServices" Version="4.1.0" />
    <PackageReference Include="System.Runtime.InteropServices.RuntimeInformation" Version="4.0.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.1.0" IncludeAssets="All" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.0.6" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.0.2" />
    <PackageReference Include="System.Security.Cryptography.Algorithms" Version="4.2.1" />
    <PackageReference Include="System.Security.Cryptography.Cng" Version="4.2.0" />
    <PackageReference Include="System.Security.Cryptography.Encoding" Version="4.0.0" />
    <PackageReference Include="System.Security.Cryptography.Primitives" Version="4.0.0" />
    <PackageReference Include="System.Security.Cryptography.X509Certificates" Version="4.1.0" />
    <PackageReference Include="System.Security.Cryptography.OpenSsl" Version="4.0.1" />
    <PackageReference Include="AWSSDK.SimpleNotificationService" Version="3.3.0.23" />
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="0.10.2-preview1" />
    <PackageReference Include="Amazon.Lambda.Logging.AspNetCore" Version="1.1.0" />
    <PackageReference Include="Amazon.Lambda.Tools" Version="1.9.0" />
