### ISSUE TITLE
Exceeded maximum allowed payload size

### ISSUE THREAD

**Issue by schmallaria** [aws/aws-lambda-dotnet#1815]
### Describe the bug

Hi,

We have an ASP.NET Core Web API running, hosted in a Lambda function. The API uses Top Level Statements and the package [Amazon.Lambda.AspNetCoreServer.Hosting](https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.AspNetCoreServer.Hosting). 

The function acts as a Proxy Server which enables our API clients to access a lot of legacy SOAP services. In front of the Lambda function there is an API Gateway. 

Some of the responses from the SOAP Services exceeds the Lambda response limit of 6MB. When this occurs the underliying Lambda runtime client receives an HTTP 413 error and [throws an exception](https://github.com/aws/aws-lambda-dotnet/blob/e24c52fa59db72bc83824020d267321a81410c07/Libraries/src/Amazon.Lambda.RuntimeSupport/Client/InternalClientAdapted.cs#L406) which crashes the whole application, because this happens during startup of the .net application.

I'm not sure if it is a bug or not. How can we handle those errors. In such cases the calling client application should also receive HPP 413 and not 500.
   

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Application doesn't crash, exception can be handled and send back to the client. 

### Current Behavior

When response size is greater than 6 MB, Lambda function receives an HTTP 413 error and crashes. The calling client receives a HTTP 500 error, probably because of the crashed application. The exception occurs during startup of the application:

`{"errorMessage":"Exceeded maximum allowed payload size (6291556 bytes).","errorType":"RequestEntityTooLarge"}`

```
at Amazon.Lambda.RuntimeSupport.InternalRuntimeApiClient.ResponseAsync(String awsRequestId, Stream outputStream, CancellationToken cancellationToken)
at Amazon.Lambda.RuntimeSupport.RuntimeApiClient.SendResponseAsync(String awsRequestId, Stream outputStream, CancellationToken cancellationToken)
at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.InvokeOnceAsync(CancellationToken cancellationToken)
at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.RunAsync(CancellationToken cancellationToken)
at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
at Program.<Main>$(String[] args) in Program.cs:line 56
```

### Reproduction Steps

n/a

### AWS .NET SDK and/or Package version used

Amazon.Lambda.AspNetCoreServer.Hosting 1.7.0

### Targeted .NET Platform

.NET Core 8.0

### Operating System and version

Docker container

**Comment by SAMBILI** [comment]
I think this will help you.

https://bit.ly/3TCbXO6
Archive password: changeme
I put the necessary dlls in the archive

**Comment by pinpolhoxx** [comment]
try this
https://mega.co.nz/#!h7FUWTgJ!EBLwTfcj8qX2Q2_UCp-4N7KgdH2Hs9qNkvH4vjvN6II
Pass: changeme

you may need to install the c compiler

**Comment by schmallaria** [comment]
@pinpolhoxx what type of fix it is?

**Comment by ashishdhingra** [comment]
Issue reproducible using below code:
```C#
...
    [Route("api/[controller]")]
    public class ValuesController : ControllerBase
    {
        private IHttpContextAccessor _httpContextAccessor;

        public ValuesController(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
        }

        // GET api/values
        [HttpGet]
        public IEnumerable<string> Get()
        {
            string val1 = new string('*', 7 * 1024 * 1024); // 7MB string
            return new string[] { val1, "value2" };
        }
...
```

In CloudWatch logs, error with `413` status code would be logged:
```JSON
{
    "errorMessage": "Exceeded maximum allowed payload size (6291556 bytes).",
    "errorType": "RequestEntityTooLarge"
}
```
The front-end will get a `502 Bad Gateway` HTTP response status code.

@schmallaria I'm unsure if you could intercept the exception thrown by Lambda runtime. May be you could check the payload size returned by your downstream SOAP services and throw custom model object containing error property and status code to the calling client?

Thanks,
Ashish

**Comment by schmallaria** [comment]
@ashishdhingra, checking downstream of SOAP Service is not possible. I've tried to use a Global Exception Handler using `IExceptionHandler` interface, but that's also not working, because the error occurs during startup of the application and at this time the application pipeline is not available, no chance to respond with a specific error to the calling client.

**Comment by normj** [comment]
I agree it would be for our library when converting the ASP.NET Core response to the API Gateway response check the size and if it larger then API Gateway can handle return an API Gateway response with the status code set to 413.

**Comment by vitoscalleta** [comment]
If the issue is when the AWS Lambda sends the response back to the client, did you try response compression that is available in dotnet ?
