### ISSUE TITLE
Using Amazon.Lambda.Core 2.4.0 breaks running locally with Amazon.Lambda.TestTool-8.0 0.15.3

### ISSUE THREAD

**Issue by thomaswr** [aws/aws-lambda-dotnet#1869]
### Describe the bug

I want to update Amazon.Lambda.Core in order to use JSON logging but this currently breaks running the lambda locally via LambdaTestTool.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

I want to update Amazon.Lambda.Core in order to use JSON logging but this currently breaks running the lambda locally via LambdaTestTool invokes lambda and I get JSON formatted as described in the blog post: https://aws.amazon.com/blogs/developer/structured-logging-for-net-lambda/

### Current Behavior

```
System.MissingMethodException: Method not found: 'Void Amazon.Lambda.Core.ILambdaLogger.LogInformation(System.String, System.Object[])'.
   at unzip_ftp_upload.Function.FunctionHandler(CloudWatchEvent`1 input, ILambdaContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at unzip_ftp_upload.Function.FunctionHandler(CloudWatchEvent`1 input, ILambdaContext context)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)

Press any key to exit
Unknown error occurred causing process exit: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
   at System.ConsolePal.ReadKey(Boolean intercept)
   at Amazon.Lambda.TestTool.TestToolStartup.ExecuteWithNoUi(LocalLambdaOptions localLambdaOptions, CommandLineOptions commandOptions, String lambdaAssemblyDirectory, RunConfiguration runConfiguration) in C:\build\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool\TestToolStartup.cs:line 175
   at Amazon.Lambda.TestTool.TestToolStartup.Startup(String productName, Action`2 uiStartup, String[] args, RunConfiguration runConfiguration) in C:\build\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool\TestToolStartup.cs:line 79
```

### Reproduction Steps

Implement Lambda using Amazon.Lambda.Core 2.4.0, making use of the ILambdaContext.Logger and using the second parameter of e.g. `LogInformation`. 
Example: `context.Logger.LogInformation("User name is: {user}", user);`
Then run it with the LambdaTestTool

### Possible Solution

Update Amazon.Lambda.Core Dependency in LambdaTestTool to 2.4.0

### AWS .NET SDK and/or Package version used

Amazon.Lambda.TestTool-8.0 0.15.3

### Targeted .NET Platform

.NET 8

### Operating System and version

Ubuntu

**Comment by ashishdhingra** [comment]
Needs reproduction. `Amazon.Lambda.Core (2.4.0)` had `RequiresPreviewFeatures` removed as part of the [commit](https://github.com/aws/aws-lambda-dotnet/commit/8fefcd7fac18bbec74119d0daa38921aded2531d#diff-9e7232fa7c46cf0affb99053e002cf5a29f7ce46a456ce74a6b5756201642210L166).

@thomaswr Please confirm if it was working with previous version `Amazon.Lambda.Core (2.3.0)`

**Comment by ashishdhingra** [comment]
Issue reproducible using Lambda Test Tool 8.0 version `0.15.3` when we use structured logging as shown below:
**Function.cs**
```C#
using Amazon.Lambda.Core;

[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer))]

namespace TestNet8Lambda;

public class Function
{
    public string FunctionHandler(string input, ILambdaContext context)
    {
        context.Logger.LogInformation("Input is: {input}", input);
        return input.ToUpper();
    }
}
```
**.csproj**
```XML
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
    <!-- This property makes the build directory similar to a publish directory and helps the AWS .NET Lambda Mock Test Tool find project dependencies. -->
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <!-- Generate ready to run images during publishing to improve cold start time. -->
    <PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="2.4.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.4.4" />
  </ItemGroup>
</Project>
```

**Comment by thomaswr** [comment]
It works with Amazon.Lambda.Core 2.3.0, if not using structured logging.
Build fails with Amazon.Lambda.Core 2.3.0, if using structured logging with:

```
error CA2252: Parameterized logging is in preview till a new version of .NET Lambda runtime client that supports parameterized logging has been deployed to the .NET Lambda managed runtime.
Till deployment has been made the feature can be used by deploying as an executable including the latest version of Amazon.Lambda.RuntimeSupport and setting the "EnablePreviewFeatures" in the Lambda project file to "true" Using 'LogInformation' requires opting into preview features.
See https://aka.ms/dotnet-warnings/preview-features for more information. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2252)
```

**Comment by normj** [comment]
Version `0.16.0` of the test tool has been released that fixes the issue. Thanks for reporting the issue.
