### ISSUE TITLE
Native image cannot be loaded multiple times: FileLoadException - using AutoMapper 5.2.0

### ISSUE THREAD

**Issue by abidalis** [aws/aws-lambda-dotnet#187]
Hi,

I'm facing following error when i use the AutoMapper 5.2.0.

> Native image cannot be loaded multiple times: FileLoadException

at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
at System.Activator.CreateInstance(Type type, Boolean nonPublic)
at System.Activator.CreateInstance(Type type)
Exception has been thrown by the target of an invocation.: TargetInvocationException
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at Microsoft.AspNetCore.Hosting.Internal.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection exportServices)
at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
at Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction..ctor()
**Native image cannot be loaded multiple times: FileLoadException**
at Microsoft.Extensions.DependencyInjection.MvcRazorMvcCoreBuilderExtensions.AddRazorViewEngineServices(IServiceCollection services)
at Microsoft.Extensions.DependencyInjection.MvcRazorMvcCoreBuilderExtensions.AddRazorViewEngine(IMvcCoreBuilder builder)
at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services)
at MyAPI.Startup.ConfigureServices(IServiceCollection services)

If i remove the AutoMapper service from the Startup.cs then it's working fine.
```
public void ConfigureServices(IServiceCollection services)
{
       services.AddAutoMapper();
}
```
Please let me know, how to fix this issue?

Thanks,
Abidali

**Comment by normj** [comment]
You didn't say what version of AutoMapper.Extensions.Microsoft.DependencyInjection you were using. That should be version 1.2.0 because newer versions require newer versions of .NET Core.

Also there is an issue with the current .NET Core Lambda with how assemblies are searched which is being fixed in the next version. Till then when you use AutoMapper you need to pass in the assemblies that contain objects to map between.

```csharp
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddAutoMapper(this.GetType().GetTypeInfo().Assembly);

...
```

**Comment by abidalis** [comment]
Hi @normj , Thanks for your help.

I'm using the correct reference in my .NETCore 1 project.
```
<PackageReference Include="AutoMapper" Version="5.2.0" />
<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="1.2.0" />
```
Adding AutoMapper as you suggested is working fine.

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddAutoMapper(this.GetType().GetTypeInfo().Assembly);
}
```
Thanks,
Abidali
