### ISSUE TITLE
'dotnet lambda package' failure after framework changing

### ISSUE THREAD

**Issue by Ruszrok** [aws/aws-lambda-dotnet#207]
Hi. Thank you for great work.
I tried to change target framework from netcoreapp1.0 to netcoreapp2.0 in my project. Everything works fine with dotnet runtime 1.0 and netcoreapp 1.0.
OS X: 10.13.2
dotnet: 2.1.4
Amazon.Lambda.Tools: 2.0.1

```dotnet lambda package``` fails with error:
```
$ dotnet lambda package -c release -f netcoreapp2.0
Executing publish command
Deleted previous publish folder
... invoking 'dotnet publish', working folder '/path-to-project/Project/src/Project.MainLambda/bin/release/netcoreapp2.0/publish'
... publish: Microsoft (R) Build Engine version 15.5.180.51428 for .NET Core
... publish: Copyright (C) Microsoft Corporation. All rights reserved.
... publish:   Restore completed in 37.11 ms for /path-to-project/Project/src/AwsLambdaOwin/AwsLambdaOwin.csproj.
... publish:   Restore completed in 36.74 ms for /path-to-project/Project/src/Project.MainLambda/Project.MainLambda.csproj.
... publish:   Restore completed in 82.82 ms for /path-to-project/Project/src/Project.MainLambda/Project.MainLambda.csproj.
... publish:   AwsLambdaOwin -> /path-to-project/Project/src/AwsLambdaOwin/bin/release/netcoreapp2.0/AwsLambdaOwin.dll
... publish:   Project.MainLambda -> /path-to-project/Project/src/Project.MainLambda/bin/release/netcoreapp2.0/Project.MainLambda.dll
... publish:   Project.MainLambda -> /path-to-project/Project/src/Project.MainLambda/bin/release/netcoreapp2.0/publish/
Changed permissions on published dll (chmod +r AWSSDK.DynamoDBv2.dll).
Changed permissions on published dll (chmod +r Amazon.Lambda.APIGatewayEvents.dll).
Changed permissions on published dll (chmod +r AWSSDK.Core.dll).
Changed permissions on published dll (chmod +r KatanaNetStandard.dll).
Changed permissions on published dll (chmod +r Nancy.dll).
Changed permissions on published dll (chmod +r Microsoft.Extensions.DependencyModel.dll).
Changed permissions on published dll (chmod +r AwsLambdaOwin.dll).
Changed permissions on published dll (chmod +r System.Text.Encodings.Web.dll).
Changed permissions on published dll (chmod +r Microsoft.DotNet.InternalAbstractions.dll).
Changed permissions on published dll (chmod +r Project.MainLambda.dll).
Changed permissions on published dll (chmod +r Newtonsoft.Json.dll).
Changed permissions on published dll (chmod +r Amazon.Lambda.Core.dll).
Changed permissions on published dll (chmod +r Microsoft.Extensions.PlatformAbstractions.dll).
Changed permissions on published dll (chmod +r Amazon.Lambda.Serialization.Json.dll).
Changed permissions on published dll (chmod +r Microsoft.IO.RecyclableMemoryStream.dll).
Flattening platform specific dependencies
... flatten: runtime/unix/lib/_._
Unknown error executing Lambda packaging: Could not find file '/path-to-project/Project/src/Project.MainLambda/bin/release/netcoreapp2.0/publish/runtime/unix/lib/_._'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo[TSafeHandle](TSafeHandle handle, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.UnixFileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at Amazon.Lambda.Tools.LambdaPackager.FlattenRuntimeFolder(IToolLogger logger, String publishLocation, JsonData depsJsonTargetNode)
   at Amazon.Lambda.Tools.LambdaPackager.CreateApplicationBundle(LambdaToolsDefaults defaults, IToolLogger logger, String workingDirectory, String projectLocation, String configuration, String targetFramework, Boolean disableVersionCheck, String& publishLocation, String& zipArchivePath)
   at Amazon.Lambda.Tools.Commands.PackageCommand.<ExecuteAsync>b__26_0()
```
I tried to publish my app using ```dotnet publish```
```
dotnet publish -c Release -o out  -f netcoreapp2.0 /p:GenerateRuntimeConfigurationFiles=true
```
Package created by dotnet is failing in runtime :
```
START RequestId: 7e478413-fd26-11e7-aa60-81012e1fd077 Version: $LATEST
An error occurred while attempting to execute your code.: LambdaException
END RequestId: 7e478413-fd26-11e7-aa60-81012e1fd0
```
Is there way to fix dotnet lambda package error or create valid package with dotnet publish?

**Comment by normj** [comment]
I suspect your `aws-lambda-tools-defaults.json` file still says netcoreapp1.0 which is what is tricking up the lambda tooling into packaging in .NET Core 1.0 format. In the stack trace you can see it going into the flatten section which it only does for .NET Core 1.0.

Can you take a look at what `framework` is set to in `aws-lambda-tools-defaults.json`? You also might need to update the `function-runtime` field to 'dotnetcore2.0`

**Comment by Ruszrok** [comment]
I have added ```"function-runtime"```. Same behavior.
```
{
  "configuration" : "Release",
  "framework" : "netcoreapp2.0",
  "function-runtime": "dotnetcore2.0"
}
```

**Comment by Ruszrok** [comment]
Package created with ```dotnet publish -c Release -o out  -f netcoreapp2.0 /p:GenerateRuntimeConfigurationFiles=true``` works great right now. Looks like there was issues in AWS environment.
 ```dotnet lambda package``` is failing with same error as above.

**Comment by stoiveyp** [comment]
Thank you @Ruszrok - just spent hours trying to stop my lambda from breaking, turns out it's fine if I use dotnet publish and upload through the browser.

**Comment by normj** [comment]
Could you guys share your project files? There must be something different about your projects that I haven't tested with.

**Comment by stoiveyp** [comment]
Not a problem. The project I was trying to deploy was at the link below. 

I tracked down the break to when I changed the PackageReference for Alexa.NET from version 1.3.0 to version 1.4.2 - I wrote most of the code between those two versions, and there's nothing there that should cause trouble.

The deploy to Lambda VS tooling succeeds with both versions, but 1.3.0 executes successfully, I get a LambdaError with 1.4.2

Both work If I zip up the publish output and upload through the browser to the Lambda directly.

https://github.com/stoiveyp/TechNottinghamAlexaSkill/tree/master/TechNottinghamAlexaSkill

**Comment by Ruszrok** [comment]
Yes, sure.
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <Description />
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <WarningsAsErrors>NU1605</WarningsAsErrors>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <WarningsAsErrors>NU1605</WarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="1.0.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.1.0" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.3.4.19" />
    <PackageReference Include="Nancy" Version="2.0.0-clinteastwood" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Amazon.Lambda.Tools" Version="1.8.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AwsLambdaOwin\AwsLambdaOwin.csproj" />
  </ItemGroup>
</Project>
```
Custom: AwsLambdaOwin
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <Authors>Damian Hickey</Authors>
    <Company />
    <PackageProjectUrl>https://github.com/damianh/AwsLambdaOwin</PackageProjectUrl>
    <PackageLicenseUrl>https://github.com/damianh/AwsLambdaOwin/blob/master/LICENSE</PackageLicenseUrl>
    <PackageTags>AWS;Amazon;Lambda;owin</PackageTags>
    <Description>Host OWIN applications in lambda.</Description>
    <RepositoryUrl>https://github.com/damianh/AwsLambdaOwin</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.APIGatewayEvents" Version="1.1.0" />
    <PackageReference Include="Amazon.Lambda.Core" Version="1.0.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.1.0" />
    <PackageReference Include="KatanaNetStandard" Version="3.0.6" />
    <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" Version="1.2.2" />
    <PackageReference Include="System.Text.Encodings.Web" Version="4.3.1" />
  </ItemGroup>

</Project>
```

**Comment by rabejens** [comment]
Glad to see that another one is having exactly the same problem. For me, I even can't use `Amazon.Lambda.Tools` newer than 1.8.1, it always says it can't resolve the package.

**Comment by normj** [comment]
@Ruszrok I cloned your AwsLambdaOwin github repository updated the targetframework to netcoreapp2.0 updated the Samples.csproj to use 2.0.1 of Amazon.Lambda.Tools and I was able to perform dotnet lambda package with no errors on a mac. Is it possible you have a left over global.json file somewhere? Could you share a repo or a branch of AwsLambdaOwin that is having the problem?


@rabejens If you are getting errors about 2.0.1 of Amazon.Lambda.Tools not being resolved then you are having a different problem. Do you have a NuGet.config that is disabling the main NuGet feed?

**Comment by Ruszrok** [comment]
@normj I am going to prepare repository this week.

**Comment by normj** [comment]
@Ruszrok Thanks!

**Comment by Ruszrok** [comment]
@normj I am unable to reproduce the issue right now. Everything works fine. I suppose that it was issue with nuget restore after framework was changed.
Close issue in dotnet cli: https://github.com/dotnet/cli/issues/2250

**Comment by normj** [comment]
Closing for lack of activity and unable to reproduce this. My best guess is a dotnet restore was not done after updating `Amazon.Lambda.Tools` because the stack trace indicates it was going down .NET Core 1.0 code paths. If anybody can provide a repo for me then we will reopen.

**Comment by Layoric** [comment]
In case anyone else comes across this, I was hitting same issue and all I needed to do was the use the AWS Console to switch from .NET Core 1.0 Runtime to .NET Core 2.0 Runtime, pushing .NET Core 2.0 code via `dotnet lambda deploy-lambda` didn't change function configuration.

![image](https://user-images.githubusercontent.com/234642/42149288-ec736f14-7e18-11e8-8b71-d73aca500fc0.png)
