### ISSUE TITLE
.Net Core 2.0 Lambda Init() doesn't get called for subsequent requests after first Init() call fails with some exception

### ISSUE THREAD

**Issue by YashChatterjee** [aws/aws-lambda-dotnet#233]
We are experiencing a big issue with AWS Lambda with .Net Core 2.0. I have tried searching and reading a lot of articles, but no resolution yet. The issue is if the Lambda Init() fails with some exception once, then the subsequent requests to this Lambda keep failing. And point to note is that Init() doesn't get called with the subsequent requests and we keep getting Http 504. Only a fresh deployment of the Lambda function fixes the issue. Unfortunately, we can't afford a fresh deployment of the same Lambda function(no code/config change) just to get around this Init() issue. Do we have a fix for this? Found a similar thread [here](https://forums.aws.amazon.com/thread.jspa?threadID=238434&tstart=0) Would appreciate some help!!

**Comment by gokarnm** [comment]
@YashChatterjee, could you provide a minimal sample code that demonstrates the issue? Could you also share the stack trace, logs from CloudWatch logs for your first invoke (please remove any confidential data).

**Comment by YashChatterjee** [comment]
@gokarnm Here is my test Lambda Init().

```
public class LambdaFunction : Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction
    {
        static int check = 0;

        protected override void Init(IWebHostBuilder builder)
        {
            Console.WriteLine("LambdaFunction Init, check count {0}", check);

            if (check == 0)
            {
                check++;
                Console.WriteLine("Incrementing check, check count now {0}", check);
                throw new ApplicationException("Throwing exception from LambdaFunction. : Application Dev");
            }

            builder
                .UseStartup<Startup>();
        }
    }
```

**Comment by YashChatterjee** [comment]
As you can see in the logs here, the console.WriteLine() didn't get called when I called the Lambda next time.
![image](https://user-images.githubusercontent.com/34089409/36566368-4d9d57c2-1849-11e8-9389-aed0bbdd1a80.png)

**Comment by ashishdhingra** [comment]
Appears to be reproducible while developing Serverless Web API using .NET Core 2.1 and Lambda. Init() is called only once:

```C#
using Microsoft.AspNetCore.Hosting;
using Amazon.Lambda.AspNetCoreServer;
using Microsoft.Extensions.Logging;
using System;

namespace LambdaMiddlewareTest
{
    public class LambdaEntryPoint : APIGatewayProxyFunction
    {
        static int check = 0;

        protected override void Init(IWebHostBuilder builder)
        {
            Console.WriteLine("LambdaFunction Init, check count {0}", check);

            if (check == 0)
            {
                check++;
                Console.WriteLine("Incrementing check, check count now {0}", check);
                throw new ApplicationException("Throwing exception from LambdaFunction. : Application Dev");
            }

            builder
                .ConfigureLogging(logging => 
                {
                    logging.AddAWSProvider();
                })
                .UseStartup<Startup>();
        }
    }
}
```

**CloudWatch Logs:**
```

2020-10-19T16:50:09.653-07:00	START RequestId: 233e2a48-51bd-40d4-b4c1-4a4402c55309 Version: $LATEST
2020-10-19T16:50:09.653-07:00	LambdaFunction Init, check count 0
2020-10-19T16:50:09.653-07:00	Incrementing check, check count now 1
2020-10-19T16:50:09.837-07:00	An exception was thrown when the constructor for type 'LambdaMiddlewareTest.LambdaEntryPoint' was invoked. Check inner exception for more details.: LambdaException at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor) at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache) Throwing exception from LambdaFunction. : Application Dev: ApplicationException at LambdaMiddlewareTest.LambdaEntryPoint.Init(IWebHostBuilder builder) in C:\Users\ashdhin\source\repos\LambdaMiddlewareInitTest\LambdaMiddlewareTest\LambdaEntryPoint.cs:line 14 at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2.Start()
2020-10-19T16:50:09.938-07:00	END RequestId: 233e2a48-51bd-40d4-b4c1-4a4402c55309
2020-10-19T16:50:09.938-07:00	REPORT RequestId: 233e2a48-51bd-40d4-b4c1-4a4402c55309 Duration: 236.44 ms Billed Duration: 300 ms Memory Size: 256 MB Max Memory Used: 63 MB Init Duration: 288.74 ms
2020-10-19T16:52:37.574-07:00	START RequestId: 201931d7-0532-40cf-bcce-a7ac3dae7e0b Version: $LATEST
2020-10-19T16:52:37.578-07:00	An exception was thrown when the constructor for type 'LambdaMiddlewareTest.LambdaEntryPoint' was invoked. Check inner exception for more details.: LambdaException at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor) at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache) Throwing exception from LambdaFunction. : Application Dev: ApplicationException at LambdaMiddlewareTest.LambdaEntryPoint.Init(IWebHostBuilder builder) in C:\Users\ashdhin\source\repos\LambdaMiddlewareInitTest\LambdaMiddlewareTest\LambdaEntryPoint.cs:line 14 at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2.Start()
2020-10-19T16:52:37.578-07:00	END RequestId: 201931d7-0532-40cf-bcce-a7ac3dae7e0b
2020-10-19T16:52:37.578-07:00	REPORT RequestId: 201931d7-0532-40cf-bcce-a7ac3dae7e0b Duration: 0.90 ms Billed Duration: 100 ms Memory Size: 256 MB Max Memory Used: 63 MB
2020-10-19T16:54:01.473-07:00	START RequestId: 0c27c5cf-cd3a-4da1-8fc4-d3a9dab91845 Version: $LATEST
2020-10-19T16:54:01.476-07:00	An exception was thrown when the constructor for type 'LambdaMiddlewareTest.LambdaEntryPoint' was invoked. Check inner exception for more details.: LambdaException at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor) at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache) Throwing exception from LambdaFunction. : Application Dev: ApplicationException at LambdaMiddlewareTest.LambdaEntryPoint.Init(IWebHostBuilder builder) in C:\Users\ashdhin\source\repos\LambdaMiddlewareInitTest\LambdaMiddlewareTest\LambdaEntryPoint.cs:line 14 at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2.Start()
2020-10-19T16:54:01.477-07:00	END RequestId: 0c27c5cf-cd3a-4da1-8fc4-d3a9dab91845
2020-10-19T16:54:01.477-07:00	REPORT RequestId: 0c27c5cf-cd3a-4da1-8fc4-d3a9dab91845 Duration: 0.89 ms Billed Duration: 100 ms Memory Size: 256 MB Max Memory Used: 64 MB
```

Looks like the exception is cached and `Init()` is never called again since there is no line with text `LambdaFunction Init, check count 1`.

**Comment by ashishdhingra** [comment]
Hi @YashChatterjee,

Good morning.

Looks like the issue is fixed when using Lambda Serverless template with .NET Core 3.1. Here is the screenshot from CloudWatch:

<img width="1638" alt="Screen Shot 2020-10-20 at 12 21 15 PM" src="https://user-images.githubusercontent.com/67916761/96634125-e802e980-12ce-11eb-87fc-d7c8e25398b8.png">

As you could see that the `Init()` is called multiple times. Also it appears that the application domain/assembly is reloaded since the `static` count field is reinitialized to 0.

**.csproj file**
```XML
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
    <AssemblyName>Issue233_LambdaInitCore</AssemblyName>
    <RootNamespace>Issue233_LambdaInitCore</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="3.3.110.58" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.3.100.1" />
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="5.1.0" />
  </ItemGroup>
</Project>
```

Please verify the above finding using .NET Core 3.1 template and confirm if this issue could be closed.

Thanks,
Ashish
