### ISSUE TITLE
Can .net core Lambda application access certificate directory?

### ISSUE THREAD

**Issue by jasondaicoder** [aws/aws-lambda-dotnet#244]
Hi guys,

I have a .net core 2.0 application which is built as Lambda and needs to access the certificate store as below

```c#
var store = new X509Store(StoreName.My, StoreLocation.CurrentUser);
store.Open(OpenFlags.ReadWrite);
store.Add(cert);
store.Close();
```

When the service launches, I got the below exceptions

```c#
at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
at System.Activator.CreateInstance(Type type, Boolean nonPublic)
at System.Activator.CreateInstance(Type type)
Read-only file system: IOException
at System.IO.UnixFileSystem.CreateDirectory(String fullPath)
at System.IO.Directory.CreateDirectory(String path)
at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.Add(ICertificatePal certPal)
at System.Security.Cryptography.X509Certificates.X509Store.Add(X509Certificate2 certificate)
```

I wonder if it's because AWS doesn't allow Lambda service to access some certain resources/directories.

The original question was raised at https://github.com/aspnet/Home/issues/2965

Any suggestions?

Thanks

Jason

**Comment by jasondaicoder** [comment]
UPDATE:

I was suggested by @natemcmaster to set HOME to be the /tmp folder. I added "HOME" with value "/tmp" in environment variable settings of Lambda Console. Is it possible to set the HOME folder like that?

**Comment by jasondaicoder** [comment]
Per my testing, setting "HOME" environment works.

**Comment by jasondaicoder** [comment]
With the solution provided by @natemcmaster. Issue resolved.
