### ISSUE TITLE
Getting a Platform Not supported exception error while trying to fetch a list of Aliases from AmazonKeyManagementServiceClient

### ISSUE THREAD

**Issue by eurojulien** [aws/aws-lambda-dotnet#268]
Hi, i am trying to fetch the Aliases from the `AmazonKeyManagementServiceClient` using a valid endPoint. 

I tried to fetch the list of aliases from the AWS CLI (aws kms list-aliases) and it works perfectly.

**Here is my code**:
private static void SelectEncryptionKey()
{
            var kmsClient = new AmazonKeyManagementServiceClient(currentRegionEndPoint);
            var keysList = kmsClient.ListAliases(new ListAliasesRequest());
}

--> I am not sure what parameters the ListAliasesRequest should have though

**Here is my config**:
Target framework is ASP.Net Core 2.0
AWSSDK version is 2.3.55.2
OS : Windows 10

**Here is the stack trace**:
`Exception has occurred: CLR/System.PlatformNotSupportedException
An unhandled exception of type 'System.PlatformNotSupportedException' occurred in AWSSDK.dll: 'Operation is not supported on this platform.'
   at System.Security.Cryptography.KeyedHashAlgorithm.Create(String algName)
   at Amazon.Util.CryptoUtilFactory.CryptoUtil.HMACSignBinary(Byte[] data, Byte[] key, SigningAlgorithm algorithmName)
   at Amazon.Runtime.Internal.Auth.AWS4Signer.ComposeSigningKey(String awsSecretAccessKey, String region, String date, String service)
   at Amazon.Runtime.Internal.Auth.AWS4Signer.ComputeSignature(String awsAccessKey, String awsSecretAccessKey, String region, DateTime signedAt, String service, String signedHeaders, String canonicalRequest, RequestMetrics metrics)
   at Amazon.Runtime.Internal.Auth.AWS4Signer.SignRequest(IRequest request, ClientConfig clientConfig, RequestMetrics metrics, String awsAccessKeyId, String awsSecretAccessKey)
   at Amazon.Runtime.Internal.Auth.AWS4Signer.Sign(IRequest request, ClientConfig clientConfig, RequestMetrics metrics, String awsAccessKeyId, String awsSecretAccessKey)
   at Amazon.Runtime.Internal.Signer.SignRequest(IRequestContext requestContext)
   at Amazon.Runtime.Internal.Signer.PreInvoke(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Signer.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.AmazonServiceClient.Invoke[TRequest,TResponse](TRequest request, IMarshaller`2 marshaller, ResponseUnmarshaller unmarshaller)
   at Amazon.KeyManagementService.AmazonKeyManagementServiceClient.ListAliases(ListAliasesRequest request)
   at InternalTool.AWSKeyServices.AWSKeyService.SelectEncryptionKey() in C:\GIT\InternalTool\AWSKeyService.cs:line 97
   at InternalTool.AWSKeyServices.AWSKeyService.Application() in C:\GIT\InternalTool\AWSKeyService.cs:line 53
   at InternalTool.Program.Main(String[] args) in C:\GIT\InternalTool\Program.cs:line 11
`

Thanks a lot ^^

**Comment by vellozzi** [comment]
Is this issue related to using AWS Lambda?  If not, can you close it and open one in the https://github.com/aws/aws-sdk-net repo?

**Comment by normj** [comment]
Closing for lack of activity
