### ISSUE TITLE
Basic Lambda to S3 or EC2 Param store timeouts. US-East-1

### ISSUE THREAD

**Issue by panodk** [aws/aws-lambda-dotnet#269]
Hey there.  I've recently noticed strange timeouts when calling basic operations of EC2-Parameter Store
and S3 (get/put).  .Net Core 2.0 in US-East-1

*Basic function to pull out of EC2Param Store:*
```        
public static async Task<string> GetValParamStore(AmazonSimpleSystemsManagementClient clientStore, string paramName, bool withDecryption)
        {
            try
            {
                if (clientStore != null)
                {
                    var parameter = new GetParameterRequest() { Name = paramName, WithDecryption = withDecryption };
                    var respo = await clientStore.GetParameterAsync(parameter);
                    return respo.Parameter.Value;

                }
                else
                {
                    Console.WriteLine("clientStore is null");
                    return null;
                }

            }
            catch (Exception e)
            {
                Console.WriteLine("GetValParamStore error:" + e);
                return null;

            }
        }
```

*Related EC2-Param store timeout error in Cloudwatch:*
```

23:45:20
START RequestId: df2f89dc-0b2f-414a-9449-4d5717553305 Version: $LATEST

23:47:00
GetValParamStore error:System.Threading.Tasks.TaskCanceledException: A task was canceled.

23:47:00
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

23:47:00
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

23:47:00
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()

23:47:00
at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()

23:47:00
--- End of stack trace from previous location where exception was thrown ---

23:47:00
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

23:47:00
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

23:47:00
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

23:47:00
at Amazon.Runtime.HttpWebRequestMessage.<GetResponseAsync>d__20.MoveNext()

23:47:00
--- End of stack trace from previous location where exception was thrown ---

23:47:00
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

23:47:00
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

23:47:00
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

23:47:00
at Amazon.Runtime.Internal.HttpHandler`1.<InvokeAsync>d__9`1.MoveNext()

23:47:00
--- End of stack trace from previous location where exception was thrown ---

23:47:00
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

23:47:00
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

23:47:00
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

23:47:00
at Amazon.Runtime.Internal.Unmarshaller.<InvokeAsync>d__3`1.MoveNext()

23:47:00
--- End of stack trace from previous location where exception was thrown ---

23:47:00
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

23:47:00
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

23:47:00
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

23:47:00
at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5`1.MoveNext()

23:47:00
--- End of stack trace from previous location where exception was thrown ---

23:47:00
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

23:47:00
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

23:47:00
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

23:47:00
at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()

23:47:00
--- End of stack trace from previous location where exception was thrown ---

23:47:00
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

23:47:00
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

23:47:00
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

23:47:00
at Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7`1.MoveNext()

23:47:00
--- End of stack trace from previous location where exception was thrown ---

23:47:00
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

23:47:00
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

23:47:00
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

23:47:00
at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()

23:47:00
--- End of stack trace from previous location where exception was thrown ---

23:47:00
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

23:47:00
at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()

23:47:00
--- End of stack trace from previous location where exception was thrown ---

23:47:00
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

23:47:00
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

23:47:00
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

23:47:00
at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()

23:47:00
--- End of stack trace from previous location where exception was thrown ---

23:47:00
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

23:47:00
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

23:47:00
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

23:47:00
at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()

23:47:00
--- End of stack trace from previous location where exception was thrown ---

23:47:00
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

23:47:00
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

23:47:00
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

23:47:00
at Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext()

23:47:00
--- End of stack trace from previous location where exception was thrown ---

23:47:00
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

23:47:00
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

23:47:00
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

23:47:00
at Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1`1.MoveNext()

23:47:00
--- End of stack trace from previous location where exception was thrown ---

23:47:00
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

23:47:00
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

23:47:00
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

23:47:00
at XYZ.Utilities.Functions.<GetValParamStore>d__11.MoveNext()

23:47:00
filename2:2b188b7b-ZZZZZZZZZZZZZZZZZZZZZZZ

23:47:00
One or more errors occurred. (Error making request with Error Code BadRequest and Http Status Code BadRequest. No further error information was returned by the service.): AggregateException at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) at lambda_method(Closure , Stream , Stream , LambdaContextInternal ) at Amazon.Runtime.Internal.HttpErrorResponseExce

23:47:00
END RequestId: df2f89dc-0b2f-414a-9449-4d5717553305
 

23:47:00
REPORT RequestId: df2f89dc-0b2f-414a-9449-4d5717553305	Duration: 100577.15 ms	Billed Duration: 100600 ms Memory Size: 512 MB	Max Memory Used: 58 MB
```

*Similar timeout error in S3:*
```
00:31:41
START RequestId: b0bf19d0-76c7-4db5-b598-af7efb9ef3e9 Version: $LATEST
00:31:44
ECHO=arn:aws:lambda:us-east-1:***************************
00:31:44
ECHO=arn:aws:lambda:us-east-1:***************************
00:31:44
filename:2b188b7b-ZZZZZZZZZZZZZZZZZZZZZZZZZ
00:31:44
attemptCount:1
00:31:44
bucketName={bucketName}
00:31:44
2
00:32:11
END RequestId: b0bf19d0-76c7-4db5-b598-af7efb9ef3e9
00:32:11
REPORT RequestId: b0bf19d0-76c7-4db5-b598-af7efb9ef3e9	Duration: 30030.16 ms	Billed Duration: 30000 ms Memory Size: 512 MB	Max Memory Used: 49 MB
00:32:11
2018-05-03T05:32:11.579Z b0bf19d0-76c7-4db5-b598-af7efb9ef3e9 Task timed out after 30.03 seconds
```

**Comment by normj** [comment]
Is this still happening? Is it happening for every request or just some requests?

**Comment by panodk** [comment]
I'm going to close the thread. It is no longer occurring but we encountered a similar event a few days later.  AWS support didn't find any issues with the infrastructure during that time and attributed the incident to the occasional network latency.
