### ISSUE TITLE
Question: Serverless App that can accept API Gateway and SNS as triggers

### ISSUE THREAD

**Issue by AndyBevan** [aws/aws-lambda-dotnet#286]
I'm trying to build a Serverless App that can handle API Gateway and SNS as triggers.

I've got the app uploaded, and the rest calls through the API Gateway work perfectly.  I've then hooked up SNS as a trigger and then connected it to my SNS Topic.  I'm then publishing requests to the topic using c# and the SDK's AmazonSimpleNotificationServiceClient.  I'm finding that I get the following error:-

```
One or more errors occurred. (Object reference not set to an instance of an object.): AggregateException
at System.Threading.Tasks.Task1.GetResultCore(Boolean waitCompletionNotification)
at lambda_method(Closure , Stream , Stream , LambdaContextInternal )

at Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction.MarshallRequest(InvokeFeatures features, APIGatewayProxyRequest apiGatewayRequest, ILambdaContext lambdaContext)
at Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction.<FunctionHandlerAsync>d__13.MoveNext()
```

The same error is reported here, https://github.com/aws/aws-lambda-dotnet/issues/168, but in that situation the user wasn't sending the correct request.  

When looking at the difference between the json when I send through SNS vs API Gateway is clear, the json request isn't the same at all.  The raw JSON of the deserialized APIGatewayProxyRequest is missing all the HTTP stuff. So when the APIGatewayProxyFunction::MarshallRequest method tries to do its thing (like try to obtain the resource path and swap out the /{proxy+} value the proper value, work with the headers, etc.) it fails with the error above. 

I tried overloading the function handler but I received errors that there were two handlers and if I wanted to do that I needed to define the functions explicitly. 
 
I then tried including a generic handler that accepts a Newtonsoft JObject and maybe that's the right direction?  Should I do that, figure out which actual type is being called and then call the underlying function handler - i.e. my own for type SNSEvent and another for APIGatewayProxyRequest?
 
I tried using the following code, SNS requests return SNSEvent,  sending an APIGatewayProxyRequest returns "No Result"

````public string ValidateSchema(JObject jObject)
{
      string result = "No Result";
      var generator1 = new JsonSchemaGenerator();
      var generator2 = new JsonSchemaGenerator();
      var schema1 = generator1.Generate(typeof(SNSEvent));
      var schema2 = generator2.Generate(typeof(APIGatewayProxyRequest));
      if (Newtonsoft.Json.Schema.Extensions.IsValid(jObject, schema1))
      {
        result = "SNSEvent";
      }
      else if (Newtonsoft.Json.Schema.Extensions.IsValid(jObject, schema2))
      {
        result = "APIGatewayProxyRequest";
      }
      return result;
}`

I'm looking for some guidance on how to trigger both from SNS and and APIGateway

**Comment by normj** [comment]
Closing for lack of activity. It sounds like you are trying to force SNS into the wrong use case of creating the request that an API Gateway would send. I would recommend putting what ever is the shared code you want to run with API Gateway handler and SNS into a shared library and then create separate Lambda functions handling the 2 different event sources. Remember the number of Lambda functions doesn't affect the cost of using Lambda.

**Comment by Neelabhra08** [comment]
@AndyBevan I am designing a quite similar application and facing the same issue. Did you find the solution to you problem? What did you decide to follow then?

@normj I am routing the request to the handler I want to. If it is a SQS event I am routing it to SQS handler and if it a APIGateway request I am trying to route it to the webapi project with the controllers (Dotnet style). Is this usecase not valid? Can't we handle two of the events with one Lambda?

public async Task FunctionHandler(object input, ILambdaContext context)
{
    try
    {
        string json = JsonSerializer.Serialize(input);

        if (json.Contains("Records") && json.Contains("aws:sqs"))
        {
            await HandleSqsRequest(json, context);
        }
        else
        {
            await HandleApiRequest(json, context);
        }
    }
}
