### ISSUE TITLE
"Unknown error" when running deploy-function --disable-interactive

### ISSUE THREAD

**Issue by loop-evgeny** [aws/aws-lambda-dotnet#298]
```
dotnet lambda deploy-function --disable-interactive

Amazon Lambda Tools for .NET Core applications (2.2.0)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet

Unknown error: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Amazon.Common.DotNetCli.Tools.Commands.CommandInfo`1.CreateCommand(IToolLogger logger, String workingDirectory, String[] args)
   at Amazon.Common.DotNetCli.Tools.CLi.Application.Execute(String[] args)
```

**Comment by normj** [comment]
The framework I have for running these commands doesn't currently support switches with no parameters. So you need to pass in `--disable-interactive true`. I agree we need to fix it so at least it has a better error message and additionally assume --disable-interactive with no value means true.

**Comment by loop-evgeny** [comment]
Thanks, `--disable-interactive true` works.

**Comment by normj** [comment]
Latest version now gives correct error message
