### ISSUE TITLE
Error when using test tool with default serverless application template 

### ISSUE THREAD

**Issue by Twistplay** [aws/aws-lambda-dotnet#398]
Hi,

I am seeing the following error when using the lambda test tool with an unmodified project generated from  the "AWS Serverless Application (.NET Core)" template.

The error seems to occur because bundleconfig.json (which is in the same folder as aws-lambda-tools-default.json) is a json array, i.e. the file opens and closes with [ and ], rather than { }, cause property lookup to fail.   Even though bundleconfig.json is unrelated to the the test tools config, it parses all jsons in the same folder to try to find the one it wants.    

Should be easy enough to fix by checking if it is a dictionary before accessing properties in SearchForConfigFiles ?

Here's the error:

Unknown error occurred causing process exit: Instance of JsonData is not a dictionary
   at LitJson.JsonData.EnsureDictionary() in E:\JenkinsWorkspaces\Lam\LambdaSandboxCoreCLRApi\Tools\LambdaTestTool\Amazon.Lambda.TestTool\ThirdParty\Json\JsonData.cs:line 721
   at Amazon.Lambda.TestTool.Program.SearchForConfigFiles(String lambdaFunctionDirectory) in E:\JenkinsWorkspaces\Lam\LambdaSandboxCoreCLRApi\Tools\LambdaTestTool\Amazon.Lambda.TestTool\Program.cs:line 92
   at Amazon.Lambda.TestTool.Program.Main(String[] args) in E:\JenkinsWorkspaces\Lam\LambdaSandboxCoreCLRApi\Tools\LambdaTestTool\Amazon.Lambda.TestTool\Program.cs:line 51

Thanks,

Adrian

**Comment by normj** [comment]
Thanks for reporting the issue. I'll get that fixed up.

**Comment by normj** [comment]
Version 0.9.1 of the tool is was released with the fix. Thanks for reporting the issue.
