### ISSUE TITLE
Cannot call DynamoDB LoadTable from xUnit test

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#411]
If you attempt to call Table.LoadTable from an xUnit [Fact] method, you receive "Object reference not set to an instance of an object."

I have a DynamoDB Class library to put an item that when called via an API in the controller works fine, but when the same method is called via xUnit test it fails with a null reference in Table.LoadTable(client, tablename).

Prior to this, the lines:

            DynamoDBContext db = new DynamoDBContext(dbClient);
            Document document = db.ToDocument(entity);

work fine.

**Comment by klaytaybai** [comment]
How/where are you initializing your client in your tests?  Could you please provide a stack trace?

**Comment by genifycom** [comment]
Client is initialized as follows:

        private static readonly AmazonDynamoDBClient client = new AmazonDynamoDBClient(aws_access_key, aws_secret_key, Amazon.RegionEndpoint.USEast1);

Stack trace is as follows:

   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.ProcessEndpointDiscovery(IRequestContext requestContext, Boolean evictCacheKey, Uri evictUri) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\EndpointDiscoveryHandler.cs:line 183
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.DiscoverEndpoints(IRequestContext requestContext, Boolean evictCacheKey) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\EndpointDiscoveryHandler.cs:line 150
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\EndpointDiscoveryHandler.cs:line 40
   at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\RetryHandler\RetryHandler.cs:line 74
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 46
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 46
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\ErrorCallbackHandler.cs:line 39
   at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\MetricsHandler.cs:line 40
   at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\RuntimePipeline.cs:line 136
   at Amazon.Runtime.AmazonServiceClient.Invoke[TResponse](AmazonWebServiceRequest request, InvokeOptionsBase options) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\AmazonServiceClient.cs:line 203
   at Amazon.DynamoDBv2.DocumentModel.Table.DescribeTable(String tableName) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DocumentModel\Table.cs:line 328
   at Amazon.Runtime.Internal.Util.Cache`2.GetValueHelper(TKey key, Boolean& isStaleItem, Func`2 creator) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\Util\SdkCache.cs:line 428
   at Amazon.DynamoDBv2.DocumentModel.Table.LoadTableInfo() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DocumentModel\Table.cs:line 133
   at Amazon.DynamoDBv2.DocumentModel.Table.LoadTable(IAmazonDynamoDB ddbClient, String tableName) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DocumentModel\Table.cs:line 425

**Comment by normj** [comment]
Can you look in the deps.json file that will be created for the xunit project and see which exact versions of AWSSDK.Core and AWSSDK.DynamoDBv2 are being used?

**Comment by genifycom** [comment]
This is what is in the csproj file. Does that help?

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.3.17.10" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="2.2.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.0.1" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

**Comment by genifycom** [comment]
Sorry, paste from before did not work.

<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.3.17.12" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="2.2.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.0.1" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>

**Comment by genifycom** [comment]
Arrgh, second paste did not work either.

'<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.3.17.12" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="2.2.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.0.1" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BVData\BVData.csproj" />
    <ProjectReference Include="..\BVReporting\BVReporting.csproj" />
    <ProjectReference Include="..\BVUtilities\BVUtilities.csproj" />
  </ItemGroup>

</Project>'

**Comment by genifycom** [comment]
#<Project Sdk="Microsoft.NET.Sdk">

#<PropertyGroup>
#<TargetFramework>netcoreapp2.1</TargetFramework>
    #<IsPackable>false</IsPackable>
#</PropertyGroup>

#<ItemGroup>
    #<PackageReference Include="AWSSDK.DynamoDBv2" Version="3.3.17.12" />
    #<PackageReference Include="Microsoft.Extensions.Logging" Version="2.2.0" />
    #<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.0.1" />
    #<PackageReference Include="xunit" Version="2.4.1" />
    #<PackageReference Include="xunit.runner.visualstudio" Version="2.4.1">
      #<PrivateAssets>all</PrivateAssets>
      #<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    #</PackageReference>
#</ItemGroup>
#</Project>

**Comment by normj** [comment]
What I want to look at is if there is some version incompatibility issue between the version of AWSSDK.Core and AWSSDK.DynamoDBv2. Which is why I want to see the versions that are resolved in the deps.json file.

**Comment by genifycom** [comment]
Hi Norm,

I do not see a deps.json The only time I see this is in a publish directory i.e. project-name.deps.json in win10-x64 for example.

That is why I sent the csproj.

Am I missing something here? These projects were created purely with Visual Studio, no command line commands. Creating a new "AWS Serverless Application with Tests" in Visual Studio Community 15.9.11 produces no deps.json file.

Thanks,
Dave

**Comment by ashishdhingra** [comment]
Hi @genifycom,

Good afternoon.

I was going through the list of backlog items and came across this issue. I see that there has not been any activity on this issue for quite some time, hence wanted to check with you if it's still an issue. In case if it's no longer an issue, please confirm if this issue could be closed.

Thanks,
Ashish
