### ISSUE TITLE
API Gateway to Lambda function returning 502 

### ISSUE THREAD

**Issue by mmillican** [aws/aws-lambda-dotnet#420]
ASP.NET Core Version 2.1

I am attempting to deploy a ASP.NET Core serverless function to API gateway via Cloudformation. 

I used the following command to package the API for deployment:

```
dotnet lambda package -pl ../src/MyProject.Api -o ../_deploy/MyProject.Api.zip
```

and the relevant bit of the CFN template is (used the AWS CLI to deploy the stack):

```yaml
ApiLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'MyProject.Api::MyProject.Api.LambdaEntryPoint::FunctionHandlerAsync'
      Runtime: dotnetcore2.1
      CodeUri: 's3://myproject-deploy/MyProject.Api/MyProject.Api.zip'
      MemorySize: 256
      Timeout: 30
      # Role: null
      Policies:
        - AWSLambdaFullAccess
      Environment:
        Variables:
          ReportTable: !Ref ReportTable
          ASPNETCORE_ENVIRONMENT: Development
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: '/{proxy+}'
            Method: ANY
        RootResource:
          Type: Api
          Properties:
            Path: /
            Method: ANY
```

Whenever I make a request to the API, I get a `502 Bad Gateway` response, with the body:

```json
{
    "message": "Internal server error"
}
```

Upon looking at the Cloudwatch logs, I'm seeing an access denied error to `appsettings.json` file. I've verified the file exists in my package.

Full stack trace of error:

```
An exception was thrown when the constructor for type 'MyProject.Api.LambdaEntryPoint' was invoked. Check inner exception for more details.: LambdaException


at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
Access to the path '/var/task/appsettings.json' is denied.: UnauthorizedAccessException
at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
at Microsoft.Extensions.FileProviders.Physical.PhysicalFileInfo.CreateReadStream()
at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2.Start()
Permission denied: IOException
```

Any tips for how to get this to work? I feel like I'm missing small, but can't get past it.

**Comment by andymac4182** [comment]
Do you have an `appsettings.json` file in the zip package?

**Comment by mmillican** [comment]
@andymac4182 Yes, it is.

**Comment by mmillican** [comment]
@normj I hate to ask, but wondering if you have any insight into this?

**Comment by sawyerit** [comment]
Have you tried setting the event integration method to POST?

**Comment by mmillican** [comment]
@sawyerit Sorry - not sure what you mean here - can you please clarify?

**Comment by sawyerit** [comment]
Yeah no worries... In your template file the event node defines the http method used for integration between API Gateway and the lambda.  Right now you have it set to ANY, but I *think* it has to be POST.  Sorry, I'm not near my computer to test out the behaviour of ANY to confirm the behaviour

**Comment by mmillican** [comment]
@sawyerit So I tested that out, and then got an Invalid authorization token, even though I don't have any auth on this API yet.

Also, the template I used was from the "serverless" templates in `dotnet new`.

**Comment by sawyerit** [comment]
@mmillican You are right. my bad, I misread that template. Sorry I couldn't be of more help.

**Comment by normj** [comment]
Can you tell me what version of Amazon.Lambda.Tools you are using? Also what OS are you running the `dotnet lambda package` command on? 

Random thought, if you were developing on windows make sure the casing of appsettings.json hasn't changed.

**Comment by mmillican** [comment]
@sawyerit no problem, thanks for the help!

@normj I'm using v3.1.1 of the tools. I did start this project on a Windows machine, but am now working on a mac. I have (case-matched):

- `appsettings.json`
- `appsettings.Development.json`

What's weird to me, is that when I did the original deploy via `dotnet lambda deploy-serverless` I _believe_ it worked fine, but when I moved it to my other stack, it stopped working. I'm still packaging it with `dotnet lambda package` though.

**Comment by mmillican** [comment]
Any other ideas I could try here?

**Comment by normj** [comment]
I can't seem to reproduce the issue. Would it be possible share a link to a zip file that repos the problem?

**Comment by mmillican** [comment]
It turns out to be some sort of file encoding issue from the `appsettings.json` file being created in Visual Studio. On my Mac, I removed the file, created a new one and added the contents back in. After deploying that latest version, it works.

I ran into similar file format issues with a CodeDeploy project I was working on a few weeks ago, so I should have thought of this earlier.

**Comment by egenita** [comment]
Hi,

I have this issue as well. I am using  .Net Core web API with 2.1.10 version.
Has this issue been resolved?

Thanks

**Comment by mmillican** [comment]
@egenita Yes. My issue was the file encoding. Make sure it doesn't have a Windows file-system line ending.

**Comment by klaytaybai** [comment]
Closing due to lack of activity
