### ISSUE TITLE
Error while invoking

### ISSUE THREAD

**Issue by kumarmohe** [aws/aws-lambda-dotnet#43]
I could deploy my existing ASP.Net Core Web API as lambda. When I tried to invoke the one of the controller methods, I get the below error.

An exception was thrown when the constructor for type '****.*Service.LambdaFunction' was invoked. Check inner exception for more details.: LambdaException

at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
at System.Activator.CreateInstance(Type type, Boolean nonPublic)
at System.Activator.CreateInstance(Type type)
Value cannot be null.
Parameter name: assembly: ArgumentNullException
at Microsoft.Extensions.DependencyModel.DependencyContextLoader.Load(Assembly assembly)
at System.Lazy`1.CreateValue()
at System.Lazy`1.LazyInitValue()
at ****.*Service.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
at Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction..ctor()

This WebAPI is working fine with AWS ECS. So I expected it should work fine here too.

Thanks,
Mohan

**Comment by normj** [comment]
Can you update to version 0.8.6-preview1 of the Amazon.Lambda.AspNetCoreServer library that I just put out this morning. It has extra logging information that might give us a better clue what is going wrong.

Also could you share the code in your Startup.cs for the ConfigureServices method?

**Comment by kumarmohe** [comment]
private const string Configurationserviceurl = "CommonConfigurationUrl";
private const string Database = "database";
private const string HashConfiguration = "hashconfiguration";
private const string CdWebUrl = "cd_web_accessurl";
private const string Aws = "aws";
private const string CdWebApi = "cdwebapi";
private const string LoanXConfiguration = "loanconfiguration";
private const string LeadServiceUrl = "leadserviceurl";


public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services.AddMvc()
               .AddJsonOptions(a => a.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver());

            List<string> configNames = new List<string>() { Database, HashConfiguration, CdWebUrl, Configurationserviceurl, Aws , LoanXConfiguration, LeadServiceUrl };

            // This condition will make sure configuration is loaded and available for other layers to consume.
            while (true)
            {
                if (ApplicationConfigurationManager.IsGivenConfigurationsExists(configNames))
                {
                    IConfigurationSection dataBaseConfig = ApplicationConfigurationManager.FetchConfiguration(Database);
                    IConfigurationSection hashconfiguration =
                        ApplicationConfigurationManager.FetchConfiguration(HashConfiguration);
                    IConfigurationSection awsConfiguration = ApplicationConfigurationManager.FetchConfiguration(Aws);
                    DependencyBuilder.BuildDependencies(services, dataBaseConfig, hashconfiguration, awsConfiguration);


                    //Enabling CORS
                    IConfigurationSection cdWebAccessUrlSection =
                        ApplicationConfigurationManager.FetchConfiguration(CdWebUrl);
                    var corsBuilder = new Microsoft.AspNetCore.Cors.Infrastructure.CorsPolicyBuilder();

                    corsBuilder.AllowAnyHeader();
                    corsBuilder.AllowAnyMethod();
                    //corsBuilder.WithOrigins(cdWebAccessUrlSection.GetValue<string>("url")); // $todo: to take multiple comma separated values from configuration.
                    corsBuilder.WithOrigins("*");
                    corsBuilder.AllowCredentials();

                    services.AddCors(options =>
                    {
                        options.AddPolicy("AllowAll", corsBuilder.Build());
                    });

                    break;
                }
            }

            services.AddApiVersioning();

            // Automapper Configuration
            services.AddAutoMapper();

            //In memory cache registeration.
            services.AddMemoryCache();

            // Inject an implementation of ISwaggerProvider with defaulted settings applied.
            services.AddSwaggerGen();

        }

**Comment by kumarmohe** [comment]
Hi Norm,

After updating to 0.8.6 preview 1, I got the below error.

An exception was thrown when the constructor for type '****.CommonService.LambdaFunction' was invoked. Check inner exception for more details.: LambdaException


at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
at System.Activator.CreateInstance(Type type, Boolean nonPublic)
at System.Activator.CreateInstance(Type type)
Value cannot be null.
Parameter name: assembly: ArgumentNullException
at Microsoft.Extensions.DependencyModel.DependencyContextLoader.Load(Assembly assembly)
at System.Lazy`1.CreateValue()
at System.Lazy`1.LazyInitValue()
at FGMC.CommonService.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
at Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction..ctor()

**Comment by danielmarston** [comment]
We're also getting the same error when using the RazorLight engine: https://github.com/toddams/RazorLight

Value cannot be null.
Parameter name: assembly: ArgumentNullException
at Microsoft.Extensions.DependencyModel.DependencyContextLoader.Load(Assembly assembly)

Our code works perfectly well when running in a dotnet core console app, however when we add it to a lambda function we get the ArgumentNullException

**Comment by ai2admin** [comment]
Hi, I'm having the same issue. https://forums.aws.amazon.com/thread.jspa?messageID=766715

Any suggestions?

**Comment by normj** [comment]
Is this issue still happening? I know there has been some changes on the service side and I'm wondering if that has addressed the issue?

**Comment by rajasekarshanmugam** [comment]
This is still happening. Assembly.GetEntryAssembly() returns a null causing above error. However, changing it to use another assembly gets past the error but blocks later when Roslyn is trying its thing. Wondering if they are all related.
