### ISSUE TITLE
Cannot publish serverless app anymore. packaging fails

### ISSUE THREAD

**Issue by lester-s** [aws/aws-lambda-dotnet#432]
Hello,

I am creating a serverless app with .Net core 2.1 using the aws .net sdk for visual studio to run it on the aws infrastructure.
Everything was working fine But now i cannot publish anymore. When i right clisk => publish to aws lambda i get this error:

`Zipping publish folder C:\GitlabRepo\Margot\.\GOTWeb_Customer\bin\Release\netcoreapp2.1\publish to C:\GitlabRepo\Margot\testPackage
Unknown error executing command: Nom de fichier ou extension trop long
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Amazon.Lambda.Tools.LambdaPackager.BundleWithBuildLambdaZip(String zipArchivePath, String rootDirectory, IDictionary`2 includedFiles, IToolLogger logger) in E:\JenkinsWorkspaces\aws-extensions-for-dotnet-cli\src\Amazon.Lambda.Tools\LambdaPackager.cs:line 548
   at Amazon.Lambda.Tools.LambdaPackager.BundleDirectory(String zipArchivePath, String sourceDirectory, Boolean flattenRuntime, IToolLogger logger) in E:\JenkinsWorkspaces\aws-extensions-for-dotnet-cli\src\Amazon.Lambda.Tools\LambdaPackager.cs:line 153
   at Amazon.Lambda.Tools.LambdaPackager.CreateApplicationBundle(LambdaToolsDefaults defaults, IToolLogger logger, String workingDirectory, String projectLocation, String configuration, String targetFramework, String msbuildParameters, Boolean disableVersionCheck, LayerPackageInfo layerPackageInfo, String& publishLocation, String& zipArchivePath) in E:\JenkinsWorkspaces\aws-extensions-for-dotnet-cli\src\Amazon.Lambda.Tools\LambdaPackager.cs:line 133
   at Amazon.Lambda.Tools.Commands.PackageCommand.PerformActionAsync()
   at Amazon.Common.DotNetCli.Tools.Commands.BaseCommand`1.ExecuteAsync() in E:\JenkinsWorkspaces\aws-extensions-for-dotnet-cli\src\Amazon.Common.DotNetCli.Tools\Commands\BaseCommand.cs:line 44`

I tried by running `dotnet lambda deploy-serverless myArgs` and `dotnet lambda package myArgs` and i get the same error.
I check all the files in my solution folder with a script and all have a path < 255.
Can you please help me find a solution ?

Regards,

Simon LE STER

**Comment by klaytaybai** [comment]
Hi @lester-s, we're sorry you are experiencing this problem.  It sounds like this [commit](https://github.com/aws/aws-extensions-for-dotnet-cli/commit/836642e4c29470772ca20c54625c17facf565dcf#diff-73f23713aeac2ab36b3512a1913e20e2) from Feb 8th might have been a breaking change?  Can you please verify that your file paths in question have remained consistent since you updated to the newer versions?

I'm going to close this issue here because the best repo is the aws-extensions-for-dotnet-cli and there is already a duplicate:  https://github.com/aws/aws-extensions-for-dotnet-cli/issues/73.  Please comment on this issue instead so we can focus the work in one place.  Thanks

**Comment by lester-s** [comment]
Thanks for your answer @klaytaybai . My path remained exactly the same. It seems possible that this commit indeed broke something. Mayabe i can try to downgrade my tool to a version from before. I'll also post on this other repo you linked me.
