### ISSUE TITLE
dotnet lambda list-serverless  Response status code does not indicate success: 404 (Not Found).

### ISSUE THREAD

**Issue by mciureanu** [aws/aws-lambda-dotnet#439]
Hello,
I'm doing the same thing on two different environments, and with the same .aws profiles stored I get different behaviors. On one environment it works fine, and on the other (AWS EC2 windows machine) when I try this:

dotnet lambda list-serverless

it gives me:

Amazon Lambda Tools for .NET Core applications (3.1.1)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet

Name                           Status               Created              Last Modifed
------------------------------ -------------------- -------------------- --------------------
Error listing AWS Serverless applications: Response status code does not indicate success: 404 (Not Found).

The same with 3.2.0.

If I try to run something like this:
dotnet lambda list-serverless --profile default

it also doesn't work, but when I create another profile named for example default1, and I copy paste the entry in the .aws file, everything works ok. So maybe I'm missing something, the profiles are cached, or something like this.  

Some background: Is this related in any way with AWS CLI? I uninstalled it, and installed the python version and then when the problems started...

**Comment by mciureanu** [comment]
Ok, I debugged the aws tools, and I get this. I don't know all the details and why aws tries to get something from http.  I got to debugging to the point to find that SharedCredentialsFile doesn't return the profile, so that's the first problem. What happens after with this http request, and why I get 404 is the 2nd problem. I couldn't debug the SharedCredentialsFile and just following the code I can't understand what can go wrong. And why is "default" string so special (if I change it to default1 it works). So I'm obviously missing something...


Amazon.Lambda.Tools.LambdaToolsException: Error listing AWS Serverless applications: System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
   at Amazon.Runtime.Internal.Util.AsyncHelpers.<>c__DisplayClass1_1`1.<<RunSync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Amazon.Runtime.Internal.Util.AsyncHelpers.ExclusiveSynchronizationContext.BeginMessageLoop() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\Util\_mobile\AsyncHelpers.cs:line 142
   at Amazon.Runtime.Internal.Util.AsyncHelpers.RunSync[T](Func`1 task) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\Util\_mobile\AsyncHelpers.cs:line 87
   at Amazon.Util.AWSSDKUtils.DownloadStringContent(Uri uri, TimeSpan timeout, IWebProxy proxy) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Util\AWSSDKUtils.cs:line 1000
   at Amazon.Util.EC2InstanceMetadata.GetItems(String relativeOrAbsolutePath, Int32 tries, Boolean slurp) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Util\_bcl+coreclr\EC2InstanceMetadata.cs:line 513
   at Amazon.Util.EC2InstanceMetadata.get_IAMSecurityCredentials() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Util\_bcl+coreclr\EC2InstanceMetadata.cs:line 311
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.FetchCredentials() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\_bcl+coreclr\DefaultInstanceProfileAWSCredentials.cs:line 142
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentials() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\_bcl+coreclr\DefaultInstanceProfileAWSCredentials.cs:line 88
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentialsAsync() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\_bcl+coreclr\DefaultInstanceProfileAWSCredentials.cs:line 106
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CredentialsRetriever.cs:line 90
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\RetryHandler\RetryHandler.cs:line 137
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Lambda.Tools.Commands.ListServerlessCommand.PerformActionAsync() in C:\Users\Administrator\Test\aws-extensions-for-dotnet-cli-master (1)\aws-extensions-for-dotnet-cli-master\src\Amazon.Lambda.Tools\Commands\ListServerlessCommand.cs:line 66
   at Amazon.Lambda.Tools.Commands.ListServerlessCommand.PerformActionAsync() in C:\Users\Administrator\Test\aws-extensions-for-dotnet-cli-master (1)\aws-extensions-for-dotnet-cli-master\src\Amazon.Lambda.Tools\Commands\ListServerlessCommand.cs:line 70
   at Amazon.Common.DotNetCli.Tools.Commands.BaseCommand`1.ExecuteAsync() in C:\Users\Administrator\Test\aws-extensions-for-dotnet-cli-master (1)\aws-extensions-for-dotnet-cli-master\src\Amazon.Common.DotNetCli.Tools\Commands\BaseCommand.cs:line 44

**Comment by mciureanu** [comment]
Can't believe I spent so much on this. It was something related to a AppData\Local\AWSToolkit file. When I deleted it, everything was fine. I thought that's only related to visual studio, but I see AWSSDK.Core does that, which I don't understand. Anyway, this fixed the problem.

**Comment by klaytaybai** [comment]
Hi @mciureanu, thanks for the update and the feedback.  Sorry this caused frustrating complications for you.  I believe the rationale for the separate handling of profiles was due to the RegisteredAccounts.json approach existing before the shared credentials file that is now used by all of the SDKs and the CLI.  Changing the order of precedence could cause unexpected breaking changes for customers, so I think an update to this is unlikely until a new major version.
