### ISSUE TITLE
.NET Core 3.0 Preview 5 not working with Custom Runtime

### ISSUE THREAD

**Issue by normj** [aws/aws-lambda-dotnet#475]
When using .NET Core 3.0 preview 5 with the Lambda Custom Runtime. The error appears to happen when `Amazon.Lambda.RuntimeSupport` creates an `HttpClient` to make request to the Lambda service.

```
START RequestId: 2d992ea6-c50f-42dd-a1b3-ed6b166bdb05 Version: $LATEST

Unhandled Exception: System.TypeInitializationException: The type initializer for 'System.Net.Http.HttpMethod' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Marvin' threw an exception. ---> System.EntryPointNotFoundException: Unable to find an entry point named '?' in shared library 'System.Native'.
   at Interop.Sys.GetNonCryptographicallySecureRandomBytes(Byte* buffer, Int32 length)
   at System.Marvin..cctor()
   --- End of inner exception stack trace ---
   at System.OrdinalIgnoreCaseComparer.GetHashCode(String obj)
   at System.Net.Http.HttpMethod.GetHashCode()
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Net.Http.HttpMethod..cctor()
   --- End of inner exception stack trace ---
   at Amazon.Lambda.RuntimeSupport.InternalRuntimeApiClient.NextAsync(CancellationToken cancellationToken)
   at Amazon.Lambda.RuntimeSupport.RuntimeApiClient.GetNextInvocationAsync()
   at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.InvokeOnceAsync()
   at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.RunAsync(CancellationToken cancellationToken)
   at CustomLambda30Preview5.Function.Main(String[] args) in C:\Users\normj\Source\Repos\CustomLambda30Preview5\CustomLambda30Preview5\Function.cs:line 21
   at CustomLambda30Preview5.Function.<Main>(String[] args)
/var/task/bootstrap: line 4:     8 Aborted                 (core dumped) /var/task/CustomLambda30Preview5
END RequestId: 2d992ea6-c50f-42dd-a1b3-ed6b166bdb05
REPORT RequestId: 2d992ea6-c50f-42dd-a1b3-ed6b166bdb05	Duration: 1621.31 ms	Billed Duration: 1700 ms 	Memory Size: 256 MB	Max Memory Used: 27 MB	
RequestId: 2d992ea6-c50f-42dd-a1b3-ed6b166bdb05 Error: Runtime exited with error: exit status 134
Runtime.ExitError
```

**Comment by normj** [comment]
The issue appears to be fixed in the recent release of .NET Core preview 6
