### ISSUE TITLE
Visual Studio custom runtime function template doesn't work

### ISSUE THREAD

**Issue by HalidCisse** [aws/aws-lambda-dotnet#479]
When I created a new custom runtime function without any code change, I got this error on the first run.
I'm following Amazon.Lambda.RuntimeSupport here 
https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.RuntimeSupport

![image](https://user-images.githubusercontent.com/6313791/59699293-4571bc80-91e9-11e9-8986-5372d5aa103f.png)

![image](https://user-images.githubusercontent.com/6313791/59698151-00e52180-91e7-11e9-85ae-4575930f4c34.png)
![image](https://user-images.githubusercontent.com/6313791/59700021-7acada00-91ea-11e9-8496-cbc01c1536e9.png)

`
 at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString, UriKind uriKind)
   at Amazon.Lambda.RuntimeSupport.InternalRuntimeApiClient.NextAsync(CancellationToken cancellationToken)
   at Amazon.Lambda.RuntimeSupport.RuntimeApiClient.GetNextInvocationAsync()
   at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.InvokeOnceAsync()
   at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.RunAsync(CancellationToken cancellationToken)
   at Lambda6.Function.Main(String[] args) in C:\Projects\Lambda6\Function.cs:line 30
`

**Comment by normj** [comment]
The Custom Runtime Project is a console application meant to run inside Lambda. The Invalid URI error message you are seeing is it failing to connect to the Lambda runtime to look for events. The console application isn't going to work locally since that endpoint won't exist.

I recommend creating the Custom Runtime Project through the **AWS Lambda Project with Tests** project template so that you will have an xUnit project to test your logic with.

![image](https://user-images.githubusercontent.com/1653751/59706880-489f8500-91b6-11e9-8ffd-aea61d792bf0.png)

**Comment by HalidCisse** [comment]
Thank you!
