### ISSUE TITLE
Microsoft.PowerShell.SDK is using 6.1.1 which is over 1 year old. Please update to latest.

### ISSUE THREAD

**Issue by lantrix** [aws/aws-lambda-dotnet#548]
During deployment of the PowerShell lambda, the `Publish-AWSPowerShellLambda` cmdlet is setting the version for `Microsoft.PowerShell.SDK` to `6.1.1`
https://github.com/aws/aws-lambda-dotnet/blob/master/PowerShell/Module/Private/_Constants.ps1#L21-L24

```PowerShell
/Users/lantrix/splunk-dbreader [dev ≡]> Publish-AWSPowerShellLambda @publishParams
Staging deployment at /var/folders/wd/55p4xfnj50lgzh5l4h3cdzym0000gp/T/Splunk-DBReader
Configuring PowerShell to version 6.1.1
Generating C# project /var/folders/wd/55p4xfnj50lgzh5l4h3cdzym0000gp/T/Splunk-DBReader/splunk-dbreader.csproj used to create Lambda function bundle.
Generating /var/folders/wd/55p4xfnj50lgzh5l4h3cdzym0000gp/T/Splunk-DBReader/Bootstrap.cs to load PowerShell script and required modules in Lambda environment.
Generating aws-lambda-tools-defaults.json config file with default values used when publishing project.
Copying PowerShell script to staging directory
Copying local module AWS.Tools.Common(4.0.0.0) from /Users/lantrix/.local/share/powershell/Modules/AWS.Tools.Common/4.0.0.0
Copying local module AWS.Tools.S3(4.0.0.0) from /Users/lantrix/.local/share/powershell/Modules/AWS.Tools.S3/4.0.0.0
Copying local module SqlServer(21.1.18179) from /Users/lantrix/.local/share/powershell/Modules/SqlServer/21.1.18179
Deploying to AWS Lambda
```

The csproj ends up having `Microsoft.PowerShell.SDK` 6.1.1 which is well over a year old.

```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netcoreapp2.1</TargetFramework>
        <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="Splunk-DBReader.ps1">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="./Modules/**">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.PowerShell.SDK" Version="6.1.1" />

        <PackageReference Include="Amazon.Lambda.Core" Version="1.0.0" />
        <PackageReference Include="Amazon.Lambda.PowerShellHost" Version="1.0.0" />
    </ItemGroup>
</Project>
```

Current version is 6.2.3
https://www.nuget.org/packages/Microsoft.PowerShell.SDK

The problem in this case, in my case, is other PowerShell core modules that have caught up to needing a minimum version from 6 months ago:

```
An exception was thrown when the constructor for type 'splunk_dbreader.Bootstrap' was invoked. Check inner exception for more details.: LambdaException

   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
This module requires PowerShell 6.2.1+. Please, upgrade your PowerShell version by checking https://aka.ms/pscore6.: WriteErrorException
   at Amazon.Lambda.PowerShellHost.PowerShellFunctionHost..ctor()
   at splunk_dbreader.Bootstrap..ctor() in /tmp/Splunk-DBReader/Bootstrap.cs:line 7```

Any chance the Publish-AWSPowerShellLambda can use something a bit more current?
`Microsoft.PowerShell.SDK` 6.2.3 has been out for 2 months at this point.
```

🙏 thanks heaps!

**Comment by normj** [comment]
I have an update I have been working on to update the default PowerShell SDK version to 6.2.3 along with updating the templates to the new modular versions of the AWS modules. I had hoped to get it done before re:Invent next week but that didn't happen so I'll have to finish it up after re:Invent.

You can use 6.2.3 today by setting the `PowerShellSdkVersion` parameter on the `Publish-AWSPowerShellLambda` cmdlet to `6.2.3`.

**Comment by lantrix** [comment]
Thanks @normj that is a great workaround, hadn't thought of that. Have fun at reinvent.
