### ISSUE TITLE
Websockets and Lambda .NET

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#553]
Hi Norm,

I was successfully using your https://github.com/normj/netcore-simple-websockets-chat-app example with .NET 2.1 and the default api URL.

Then I changed to using a Custom Name for the Websocket API (so I could use wss.mydomain.com).

However, now I get the error:

**Error posting message to D-j5-fe7IAMCKMA=: No method found matching route prod/@connections/D-j5-fe7IAMCKMA= for http method POST.**

The connection is correct in DynamoDB and I cannot see how to debug this. The stack trace is:

at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at BVWSServerSendMessage.Function.FunctionHandler(APIGatewayProxyRequest request, ILambdaContext context) in C:\Dev\SourceControl\Development\Brook-Valley-Thrift-Stores\BVTagging\BVWSServerSendMessage\Function.cs:line 135

line 135 is **await apiClient.PostToConnectionAsync(postConnectionRequest);**

I tried removing the lambda function and re-adding in the Console because of the note "In the AWS CLI and AWS SDKs, you can create routes before or after you create integrations. Currently the console does not support reuse of integrations, so you must create the route first and then create the integration for that route."

But no change. Any suggestions?

**Comment by klaytaybai** [comment]
Did you redeploy your API after making the lambda changes?

**Comment by genifycom** [comment]
The Custom Domain Name for websocket APIs has changed to make it easier to add a custom name. I added the custom name (for the prod stage) and created a CNAME using the API Gateway domain name. As per this document https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-custom-domains.html

wscat successfully connects and disconnects. The API was redeployed but I still have an issue. The error is slightly different now.

 Post to connection 0: JaHfldCgSK4CIUA=
Error posting message to JaHfldCgSK4CIUA=: No method found matching route %40connections/JaHfldCgSK4CIUA%3D for http method POST.

Stace Trace:
at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at PFWSServerSendMessage.Function.FunctionHandler(APIGatewayProxyRequest request, ILambdaContext context) 

Line executing: await apiClient.PostToConnectionAsync(postConnectionRequest);

What am I missing?

**Comment by genifycom** [comment]
Going to close this and open another one as I have more information now.

**Comment by paulfryer** [comment]
What was the solution? I'm running into this error too.

**Comment by intersides** [comment]
Me too, I am running into this issue. Any clues ?

**Comment by intersides** [comment]
For me the issue is that when using a custom domain the endpoint changes, and when I perform a apigwManagementApi.postToConnection(...) it fails  with "No method found matching route". 
I haven't find a way for the lambda to access the enpoint before the custom domain modification or any other solutions.
