### ISSUE TITLE
API Gateway HTTP API AggregateException

### ISSUE THREAD

**Issue by joshbartley** [aws/aws-lambda-dotnet#557]
Spent some time seeing if I could get a dotnet lambda function working with the new HTTP API. I kept getting an error in CloudWatch that was not in my code. I tried Amazon.Lambda.AspNetCoreServer 3.1.0 and 4.0.0. Both have the same issue. Switched over to a REST API and everything worked fine.

Cloudwatch Log
> One or more errors occurred. (Object reference not set to an instance of an object.): AggregateException
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at lambda_method(Closure , Stream , Stream , LambdaContextInternal )
   at Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction.<>c.<InternalPostCreateContext>b__6_2(KeyValuePair`2 entry)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Security.Claims.ClaimsIdentity.SafeAddClaims(IEnumerable`1 claims)
   at System.Security.Claims.ClaimsIdentity..ctor(IIdentity identity, IEnumerable`1 claims, String authenticationType, String nameType, String roleType)
   at Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction.InternalPostCreateContext(Context context, APIGatewayProxyRequest apiGatewayRequest, ILambdaContext lambdaContext)
   at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2.FunctionHandlerAsync(TREQUEST request, ILambdaContext lambdaContext)

I'm guessing that on [APIGatewayProxy Line 110](https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.AspNetCoreServer/APIGatewayProxyFunction.cs#L110) that something is being passed back as an Authorizer, so the APIGatewayProxyFunction's null check passes assuming that claims will be present, then the C# lambda for building the claims breaks.

Knowing the HTTP API is in beta, I don't know what the policy is on fixing this. Also leaving this here to document the problem.

**Comment by normj** [comment]
Thanks for reporting this issue. I have started the work of making sure the HTTP API works correctly with Amazon.Lambda.AspNetCoreServer. The work is going on in the [httpapi-support](https://github.com/aws/aws-lambda-dotnet/tree/httpapi-support) which fixes this issue. I need to spend a bit more time making sure there are no other issues.

**Comment by joshbartley** [comment]
@normj would the best way to keep testing this be to pull your branch directly into my project and use that until there is a pre-release?

**Comment by normj** [comment]
If you want to help test here is a preview built of Amazon.Lambda.AspNetCoreServer: 
https://normj-packages.s3.us-west-2.amazonaws.com/Amazon.Lambda.AspNetCoreServer.4.0.1-preview1.nupkg

**Comment by Kralizek** [comment]
> If you want to help test here is a preview built of Amazon.Lambda.AspNetCoreServer:
> https://normj-packages.s3.us-west-2.amazonaws.com/Amazon.Lambda.AspNetCoreServer.4.0.1-preview1.nupkg
A bit off topic...
Before realizing it was an s3 bucket, I thought your link was pointing to a managed package hosting system (kind of highly available, highly scalable myget)

**Comment by normj** [comment]
Version 4.1.0 of Amazon.Lambda.AspNetCoreServer has shipped with this fix. Thanks for letting us know about the issue.

**Comment by raRaRa** [comment]
My API is using version 4.1.0 of `Amazon.Lambda.AspNetCoreServer` and I still get this error message after switching to HTTP from REST in API Gateway:
```
One or more errors occurred. (Object reference not set to an instance of an object.): AggregateException
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at lambda_method(Closure , Stream , Stream , LambdaContextInternal )

   at Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction.MarshallRequest(InvokeFeatures features, APIGatewayProxyRequest apiGatewayRequest, ILambdaContext lambdaContext)
   at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2.FunctionHandlerAsync(TREQUEST request, ILambdaContext lambdaContext)
```

Any clue what may be wrong?
