### ISSUE TITLE
Incomplete Stack Trace in Cloudwatch

### ISSUE THREAD

**Issue by patoncrispy** [aws/aws-lambda-dotnet#586]
It seems I am getting an incomplete stack trace in Cloudwatch logs:

```
An exception was thrown when the constructor for type 'Redacted.FunctionHandler' was invoked. Check inner exception for more details.: LambdaException


   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
```

I've tried using `UNWRAP_AGGREGATE_EXCEPTIONS` set to true and false but that doesn't show me the inner exception.

I've tried `<PreserveCompilationContext>false</PreserveCompilationContext>` but that didn't seem to change anything either.

I've tried wrapping the content of my constructor in a try/catch block but the exception seems to be thrown before this point.

Getting the logs using the AWS CLI doesn't show any new information, either.

Is there any other way to get more detailed exceptions in this case?

Relates to https://github.com/aws/aws-lambda-dotnet/issues/114 in some ways.

**Comment by patoncrispy** [comment]
Nevermind, my constructor wasn't marked as `public`. ☹️
