### ISSUE TITLE
command-[dotnet lambda package] throws "Unknown error executing command: No such file or directory"

### ISSUE THREAD

**Issue by murthyc** [aws/aws-lambda-dotnet#592]
Running command "dotnet lambda package"
throws "Unknown error executing command: No such file or directory"
MacOS-dotnet --version -2.1.804
--------------------------------------------------
Amazon Lambda Tools for .NET Core applications (3.3.1)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet

Executing publish command
... invoking 'dotnet publish', working folder '/Users/...../MyProject/bin/Debug/netcoreapp2.1/publish'
... Disabling compilation context to reduce package size. If compilation context is needed pass in the "/p:PreserveCompilationContext=false" switch.
Unknown error executing command: No such file or directory
at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow)
at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
at System.Diagnostics.Process.Start()
at Amazon.Lambda.Tools.LambdaDotNetCLIWrapper.Publish(LambdaToolsDefaults defaults, String projectLocation, String outputLocation, String targetFramework, String configuration, String msbuildParameters, IList1 publishManifests) in C:\codebuild\tmp\output\src838309283\src\src\Amazon.Lambda.Tools\LambdaDotNetCLIWrapper.cs:line 266 at Amazon.Lambda.Tools.LambdaPackager.CreateApplicationBundle(LambdaToolsDefaults defaults, IToolLogger logger, String workingDirectory, String projectLocation, String configuration, String targetFramework, String msbuildParameters, Boolean disableVersionCheck, LayerPackageInfo layerPackageInfo, String& publishLocation, String& zipArchivePath) in C:\codebuild\tmp\output\src838309283\src\src\Amazon.Lambda.Tools\LambdaPackager.cs:line 76 at Amazon.Lambda.Tools.Commands.PackageCommand.PerformActionAsync() at Amazon.Common.DotNetCli.Tools.Commands.BaseCommand1.ExecuteAsync() in C:\codebuild\tmp\output\src838309283\src\src\Amazon.Common.DotNetCli.Tools\Commands\BaseCommand.cs:line 44

**Comment by klaytaybai** [comment]
It seems like this is an issue with the working directory

**Comment by murthyc** [comment]
Dotnet path was causing the issue.  #1 or #2 worked for me. 
1) MyProject: $ export PATH=/usr/local/share/dotnet:$PATH

Symlink : -f to force, else throws” File Exists”
2) MyProject: $ ln -sf /usr/local/share/dotnet/dotnet /usr/local/bin/
