### ISSUE TITLE
APIGatewayProxyRequest -> request is null.

### ISSUE THREAD

**Issue by RoyIL** [aws/aws-lambda-dotnet#603]
Hey there! 

I've recently started developing my application using AWS Lambda for .NET. 
I'm currently working on my project which is based on the "Blogs API" Lambda sample. 
However, when testing my Lambda GetBlogAsync() locally the APIGatewayProxyRequest request is always null. 

```        
        public async Task<APIGatewayProxyResponse> GetBlogAsync(APIGatewayProxyRequest request, ILambdaContext context)
        {
            string blogId = null;
            if (request.PathParameters != null && request.PathParameters.ContainsKey(ID_QUERY_STRING_NAME))
                blogId = request.PathParameters[ID_QUERY_STRING_NAME];
            else if (request.QueryStringParameters != null && request.QueryStringParameters.ContainsKey(ID_QUERY_STRING_NAME))
                blogId = request.QueryStringParameters[ID_QUERY_STRING_NAME];

            if (string.IsNullOrEmpty(blogId))
            {
                return new APIGatewayProxyResponse
                {
                    StatusCode = (int)HttpStatusCode.BadRequest,
                    Body = $"Missing required parameter {ID_QUERY_STRING_NAME}"
                };
            }

            context.Logger.LogLine($"Getting blog {blogId}");
            var blog = await DDBContext.LoadAsync<Blog>(blogId);
            context.Logger.LogLine($"Found blog: {blog != null}");

            if (blog == null)
            {
                return new APIGatewayProxyResponse
                {
                    StatusCode = (int)HttpStatusCode.NotFound
                };
            }

            var response = new APIGatewayProxyResponse
            {
                StatusCode = (int)HttpStatusCode.OK,
                Body = JsonConvert.SerializeObject(blog),
                Headers = new Dictionary<string, string> { { "Content-Type", "application/json" } }
            };
            return response;
        }
```
Here is the error I keep getting while testing the function in the Mock Lambda Test Tool: 

> System.NullReferenceException: Object reference not set to an instance of an object.
   at PayUS_Serverless.Functions.GetBlogAsync(APIGatewayProxyRequest request, ILambdaContext context) in C:\Users\User\source\repos\PayUS-Serverless\PayUS-Serverless\Functions.cs:line 94
   at Amazon.Lambda.TestTool.Runtime.LambdaExecutor.ProcessReturn(ExecutionRequest request, Object lambdaReturnObject) in C:\codebuild\tmp\output\src248644039\src\Tools\LambdaTestTool\Amazon.Lambda.TestTool\Runtime\LambdaExecutor.cs:line 135
   at Amazon.Lambda.TestTool.Runtime.LambdaExecutor.Execute(ExecutionRequest request) in C:\codebuild\tmp\output\src248644039\src\Tools\LambdaTestTool\Amazon.Lambda.TestTool\Runtime\LambdaExecutor.cs:line 60

Line 94 is the second code line (first If statement), I've also throwed an simple exception ``throw Exception((request == null).ToString())`` and the result was "True" (the APIGatewayProxyRequest request parameter is indeed null).

I'll be happy to provide any additional information if requested.

Thank you for your time! 😃 
Roy B.

**Comment by klaytaybai** [comment]
I was not able to reproduce this problem using an unmodified Blogs API template and the Lambda Test Tool.  When I ran the test tool with the below configuration, the request parameter was initialized.

What did you input for 'Function Input?'  It may be helpful to know the versions of any tools or AWS SDKs you are using, including the AWS Toolkit for Visual Studio version.

![image](https://user-images.githubusercontent.com/21030068/76888768-bb22bb80-6841-11ea-8502-5ae8a2ff058a.png)

**Comment by normj** [comment]
Closing for lack of activity

**Comment by devowl** [comment]
Hello, i'm newby for AWS, and have a same weird behavior. When Mock test tools calls my Function some why the request body is null. I have created serverless app based on code from Blog example

![image](https://user-images.githubusercontent.com/8266223/139597588-034cd6b4-9ab8-4788-ba7c-b9860f554fdb.png)

Here is function function config:

> "GetRates": {
>             "Type": "AWS::Serverless::Function",
>             "Properties": {
>                 "Handler": "CE.Aws.Exchange.Application::CE.Aws.Exchange.Application.ClientFunctions::GetRatesAsync",
>                 "Runtime": "dotnetcore3.1",
>                 "MemorySize": 128,
>                 "Timeout": 10,
>                 "Role": null,
>                 "Policies": [
>                     "AWSLambda_FullAccess"
>                 ],
>                 "Events": {
>                     "PutResource": {
>                         "Type": "Api",
>                         "Properties": {
>                             "Path": "/",
>                             "Method": "GET" }}}}},

**dotnet-lambda-test-tool-3.1.exe** product version is: 0.11.3
Dependencies versions:
![image](https://user-images.githubusercontent.com/8266223/139597740-989c3269-a009-4e33-a280-88aa32318cea.png)

If you need more info let me know

Thanks for any help
