### ISSUE TITLE
Unable to run SQL client code from Visual Studio 2019 AWS Serverless Application C#

### ISSUE THREAD

**Issue by alexgurmanihsm** [aws/aws-lambda-dotnet#642]
We have on premises SQL server that we need to access from .NET C# lambdas running on AWS Cloud Formation using Visual Studio 2019 AWS Serverless Application for development.

I wrote a small Hello World application that attempts to connect to database running a stored procedure. However, even running Mock Lambda Test Tool fails with an error about runtime.win-x64.runtime.native.System.Data.SqlClient.sni, see below.

 Error:
  An assembly specified in the application dependencies manifest (AWSServerlessHelloWorldEmpty.deps.json) was not found:
    package: 'runtime.win-x64.runtime.native.System.Data.SqlClient.sni', version: '4.4.0'
    path: 'runtimes/win-x64/native/sni.dll'

   at System.Runtime.Loader.AssemblyDependencyResolver..ctor(String componentAssemblyPath)
   at Amazon.Lambda.TestTool.Runtime.LambdaAssemblyLoadContext..ctor(String lambdaPath) in C:\codebuild\tmp\output\src142363207\src\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool\Runtime\LambdaAssemblyLoadContext.cs:line 28
   at Amazon.Lambda.TestTool.Runtime.LocalLambdaRuntime.Initialize(String directory, IAWSService awsService) in C:\codebuild\tmp\output\src142363207\src\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool\Runtime\LocalLambdaRuntime.cs:line 71
   at Amazon.Lambda.TestTool.Runtime.LocalLambdaRuntime.Initialize(String directory) in C:\codebuild\tmp\output\src142363207\src\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool\Runtime\LocalLambdaRuntime.cs:line 46
   at Amazon.Lambda.TestTool.TestToolStartup.Startup(String productName, Action`2 uiStartup, String[] args, RunConfiguration runConfiguration) in C:\codebuild\tmp\output\src142363207\src\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool\TestToolStartup.cs:line 77

![image](https://user-images.githubusercontent.com/64160933/80021465-29d9e100-84a0-11ea-9ced-a0ac4dc6b65e.png)

**Comment by labrev** [comment]
I ran into this same issue.  It was mentioned in two other issues.  #617 is one of them.  I added `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` in the PropertyGroup in the csproj file and that fixed the issue for me with the Mock Lambda Test Tool.

**Comment by alexgurmanihsm** [comment]
Worked!!!!

Thank you
