### ISSUE TITLE
Fail Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction[0] Using Visual Studio Net 3.0

### ISSUE THREAD

**Issue by DeniseJames** [aws/aws-lambda-dotnet#670]
I tested my NET core using localhost and Postman and I am able to `getitems` and `putitems` in my DynamoDb using an AWS Serverless template. I used the AWS publish to Lambda and the function is uploaded to AWS.  I added a policy to the Lambda role to assure it has permission to `getitems` and `putitems`. I get a 500 status error and this in the log on the Cloudwatch:

```
Executed endpoint 'AWSServerlessDynamoDb.Controllers.DynamoDbController.GetItems (AWSServerlessDynamoDb)'

17:10:52
[Information] Microsoft.AspNetCore.Routing.EndpointMiddleware: Executed endpoint 'AWSServerlessDynamoDb.Controllers.DynamoDbController.GetItems (AWSServerlessDynamoDb)'
[Information] Microsoft.AspNetCore.Routing.EndpointMiddleware: Executed endpoint 'AWSServerlessDynamoDb.Controllers.DynamoDbController.GetItems (AWSServerlessDynamoDb)' 

17:10:52
[41m[30mfail[39m[22m[49m: Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction[0]
[41m[30mfail[39m[22m[49m: Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction[0]

17:10:52
Unknown error responding to request: AmazonServiceException:
Unknown error responding to request: AmazonServiceException:

17:10:52
Amazon.Runtime.AmazonServiceException: Unable to get IAM security credentials from EC2 Instance Metadata Service.

17:10:52
at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.FetchCredentials()

17:10:52
at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentials()
```

This is the role for the lambda function:

``` json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "dynamodb:getitem",
                "dynamodb:deleteitem",
                "dynamodb:createtable",
                "dynamodb:describetable",
                "dynamodb:putitem",
                "dynamodb:updateitem"
            ],
            "Resource": "arn:aws:dynamodb:us-east-1:976999488553:table/BlogDynamoDbTable"
        }
    ]
}
```

I did google the error and it talks of an APIGATEWAY.  What else needs to be done to be able to getitems from the database?

**Comment by ashishdhingra** [comment]
Hi @DeniseJames,

Please refer the link [Troubleshoot Lambda Invoke API Errors 502 and 500](https://aws.amazon.com/premiumsupport/knowledge-center/lambda-troubleshoot-invoke-error-502-500/) for possible resolution for your issue. Kindly let us know if it helps.

Thanks,
Ashish
