### ISSUE TITLE
MOCK Lambda Test Tool - JSON parsing issues 

### ISSUE THREAD

**Issue by grahamehorner** [aws/aws-lambda-dotnet#673]
I'm experiencing the following when running a LambdaServerlessApplication, all JSON files have been verified as valid; however the tooling is failing to start/run the application.

I have also verified that the code runs as excepted using the LocalEntryPoint, which is no different to the LambdaEntry point.

NOTE: this is using the updated JSON serialization for netcoreapp3.1 as published by the Amazon.Lambda 
```
AWS .NET Core 3.1 Mock Lambda Test Tool (0.10.0)
Loaded local Lambda runtime from project output C:\Users\...\bin\Debug\netcoreapp3.1
Error parsing JSON file: C:\Users\...\bin\Debug\netcoreapp3.1\appsettings.Development.json
Error parsing JSON file: C:\Users\...\bin\Debug\netcoreapp3.1\bundleconfig.json
Error parsing JSON file: C:\Users\...\appsettings.Development.json
Found Lambda config file C:\Users\...\aws-lambda-tools-defaults.json
Error parsing JSON file: C:\Users\...\bundleconfig.json
Unknown error occurred causing process exit: Failed to bind to address http://localhost:5050.
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.Start()
   at Amazon.Lambda.TestTool.WebTester31.Startup.LaunchWebTester(LocalLambdaOptions lambdaOptions, Boolean openWindow) in C:\codebuild\tmp\output\src142363207\src\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool.WebTester31\Startup.cs:line 40
   at Amazon.Lambda.TestTool.WebTester31.Program.<>c.<Main>b__0_0(LocalLambdaOptions options, Boolean showUI) in C:\codebuild\tmp\output\src142363207\src\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool.WebTester31\Program.cs:line 19
   at Amazon.Lambda.TestTool.TestToolStartup.Startup(String productName, Action`2 uiStartup, String[] args, RunConfiguration runConfiguration) in C:\codebuild\tmp\output\src142363207\src\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool\TestToolStartup.cs:line 90
```

**Comment by ashishdhingra** [comment]
Hi @grahamehorner, 

Good afternoon.

Please see if upgrading the Mock Lambda Test tool using .NET CLI helps to resolve the issue. There are multiple versions of the tool targeting .NET Core 2.1 and 3.1 listed in the [Mock Lambda Readme](https://github.com/aws/aws-lambda-dotnet/tree/master/Tools/LambdaTestTool). For example, to update tool targeting .NET Core 3.1, execute the following command from .NET CLI:

```
dotnet tool update -g Amazon.Lambda.TestTool-3.1
```

Kindly let me know if this helps.

Thanks,
Ashish
