### ISSUE TITLE
cannot run mock test tool. ""Unknown error occurred causing process exit: Failed to bind to address http://localhost:5050"

### ISSUE THREAD

**Issue by qinking126** [aws/aws-lambda-dotnet#688]
## The Question

cannot run mock test tool. ""Unknown error occurred causing process exit: Failed to bind to address http://localhost:5050"

### Environment

* Build Version:  3.1, 0.10.0
* OS Info: window 10
* Build Environment:  visual studio 2019 community
* Targeted .NET Platform:  .net core 3.1

---

I kept getting this error message "Unknown error occurred causing process exit: Failed to bind to address http://localhost:5050". I changed the port number. it didn't help.

```
AWS .NET Core 3.1 Mock Lambda Test Tool (0.10.0)
Loaded local Lambda runtime from project output C:\projects\cyberrating-api\CyberRating.GetPremium\bin\Debug\netcoreapp3.1
Found Lambda config file C:\projects\cyberrating-api\CyberRating.GetPremium\aws-lambda-tools-defaults.json
Unknown error occurred causing process exit: Failed to bind to address http://localhost:5050.
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.Start()
   at Amazon.Lambda.TestTool.WebTester31.Startup.LaunchWebTester(LocalLambdaOptions lambdaOptions, Boolean openWindow) in C:\codebuild\tmp\output\src142363207\src\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool.WebTester31\Startup.cs:line 40
   at Amazon.Lambda.TestTool.WebTester31.Program.<>c.<Main>b__0_0(LocalLambdaOptions options, Boolean showUI) in C:\codebuild\tmp\output\src142363207\src\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool.WebTester31\Program.cs:line 19
   at Amazon.Lambda.TestTool.TestToolStartup.Startup(String productName, Action`2 uiStartup, String[] args, RunConfiguration runConfiguration) in C:\codebuild\tmp\output\src142363207\src\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool\TestToolStartup.cs:line 90
Press any key to exit
```

**Comment by NGL321** [comment]
Hey @qinking126,

My initial suggestion would be to double-check that the port is not currently in use ([see here](https://stackoverflow.com/questions/48198/how-can-you-find-out-which-process-is-listening-on-a-port-on-windows)). If it is, try a port that is not in use. If it is not, try rerunning after a reboot.

Failing both of the above suggestions, it is most likely a bug. If that is the case, could you please provide the steps you took that got you to the error (how you set up the test tool, what are you testing, etc.)?


😸 😷

**Comment by qinking126** [comment]
I already tried that.  running it after a reboot. still the same error.  I
dont know how to reproduce this bug.  I was testing a  lambda function i
built.  just clicked the mock test tool on visual studio 2019. then it
showed that error message. my coworkers tested the same project on his
computer, he had no issues.
