### ISSUE TITLE
LambdaEntryPoint fail to be constructed due to IHostingEnvironment

### ISSUE THREAD

**Issue by qkhanhpro** [aws/aws-lambda-dotnet#703]
Hi.

I am currently migrating from Netcore 2.1 to Netcore 3.1 following [this blog post](https://aws.amazon.com/blogs/compute/announcing-aws-lambda-supports-for-net-core-3-1/)

After fixing many breaking changes, the application managed to build and publish to Lambda. But Invocation throws this exception.

```
at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
Method not found: 'Microsoft.AspNetCore.Hosting.IHostingEnvironment Microsoft.AspNetCore.Hosting.WebHostBuilderContext.get_HostingEnvironment()'.: MissingMethodException
   at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2.<>c.<CreateWebHostBuilder>b__13_0(WebHostBuilderContext hostingContext, IConfigurationBuilder config)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2.Start()
   at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2..ctor(StartupMode startupMode)
   at Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction..ctor()
   at Project99BE.LambdaEntryPoint..ctor()
```

Some changes I had to made that is not documented in the blog post is inside .csproj file
```
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
    **<IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>**
  </PropertyGroup>
```
along with `runtime` and `function-runtime` in `aws-lambda-tools-defaults.json`

The only thing I see floating around is this issue opened by @normj 
https://github.com/dotnet/aspnetcore/issues/9608
But I am not sure how this affect my migration, to be honest.

My Amazon.Lambda.AspNetCoreServer is at 3.1.0
Edit: Same problem with 5.1.2

**Comment by normj** [comment]
Would it be possible to provide your full project file or the *.deps.json file from the publish folder? Seems like something is cause an older version of some of the Microsoft packages to be included that should be coming from the shared runtime.

**Comment by qkhanhpro** [comment]
This seems to be an Msbuild / Nuget issue
I cleaned the source code and nuget on build server, the lambda works fine now.
