### ISSUE TITLE
Could not load file or assembly 'mscorlib'

### ISSUE THREAD

**Issue by jstandish** [aws/aws-lambda-dotnet#72]
I'm getting the following exception when trying to execute via the API Gateway. Thoughts?

An exception was thrown when the constructor for type 'AWSServerless.LambdaEntryPoint' was invoked. Check inner exception for more details.: LambdaException

at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
at System.Activator.CreateInstance(Type type, Boolean nonPublic)
at System.Activator.CreateInstance(Type type)
Could not load file or assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.: FileNotFoundException
at AWSServerless.LambdaEntryPoint.Init(IWebHostBuilder builder)
at Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction..ctor()
at AWSServerless.LambdaEntryPoint..ctor()
Could not load the specified file.: FileNotFoundException
at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)

**Comment by normj** [comment]
Is that all that was in your logs? Could you share the dependencies from the project.json?

**Comment by jstandish** [comment]
Fixed it. 

Project.json went from this

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [ "dnxcore50", "net461", "net", "dotnet5.6", "portable-net45+win8" ]
    }
  }

to this


  "frameworks": {
    "netcoreapp1.0": {
      "imports": [ "dnxcore50"]
    }
  }

**Comment by normj** [comment]
Interesting. By importing net461 target framework moniker you probably pulled in some .NET Framework assemblies and not .NET Core assemblies.

**Comment by jstandish** [comment]
@normj Probably the case. Could be a gotcha as this worked perfectly fine with standard Lambda invocation via the API Gateway. I discovered this when converting my project to use the .NET core Web API pattern as I'm more comfortable with it.

**Comment by normj** [comment]
Closing as I believe this is answered. We'll look in the future to see how we can add more validation during the publishing of the function.
