### ISSUE TITLE
Unable to Use LambdaTestTool with latest MongoDb Driver

### ISSUE THREAD

**Issue by andreikrasnou** [aws/aws-lambda-dotnet#758]
## Description
When I'm trying to add nuget dependency on MongoDB.Driver.Core  version: '2.11.3 I'm facing with problem 

## Reproduction Steps

1. Create simple lambda .net project
2. Install MongoDB.Driver.Core  version: 2.11.3
3. Try to execute lambda 

### Logs

AWS .NET Core 3.1 Mock Lambda Test Tool (0.10.1)
Unknown error occurred causing process exit: Dependency resolution failed for component C:\Users\Andrei_Krasnou\source\repos\TestMongoConnection\TestMongoConnection\bin\Debug\netcoreapp3.1\TestMongoConnection.dll with error code -2147450740. Detailed error: Error:
  An assembly specified in the application dependencies manifest (TestMongoConnection.deps.json) was not found:
    package: 'MongoDB.Driver.Core', version: '2.11.3'
    path: 'runtimes/win/native/libzstd.dll'

   at System.Runtime.Loader.AssemblyDependencyResolver..ctor(String componentAssemblyPath)
   at Amazon.Lambda.TestTool.Runtime.LambdaAssemblyLoadContext..ctor(String lambdaPath) in C:\codebuild\tmp\output\src782171135\src\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool\Runtime\LambdaAssemblyLoadContext.cs:line 28
   at Amazon.Lambda.TestTool.Runtime.LocalLambdaRuntime.Initialize(String directory, IAWSService awsService) in C:\codebuild\tmp\output\src782171135\src\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool\Runtime\LocalLambdaRuntime.cs:line 71
   at Amazon.Lambda.TestTool.Runtime.LocalLambdaRuntime.Initialize(String directory) in C:\codebuild\tmp\output\src782171135\src\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool\Runtime\LocalLambdaRuntime.cs:line 46
   at Amazon.Lambda.TestTool.TestToolStartup.Startup(String productName, Action`2 uiStartup, String[] args, RunConfiguration runConfiguration) in C:\codebuild\tmp\output\src782171135\src\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool\TestToolStartup.cs:line 77

### Environment

* OS Info: Windows 10 
* Build Environment: Visual Studio 2019
* Targeted .NET Platform:  .net core SDK 3.1.403 (x64)

---
Could you please advise how to deal with this issue? Sorry if I miss something and this is not a bug bit in that case @normj maybe you can provide some advice how this can be resolved.

**Comment by andreikrasnou** [comment]
Found way to resolve   <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies> in csproj saved my life
