### ISSUE TITLE
'dotnet lambda package' throws 'ArgumentNullException' when running for a project with multiple target frameworks

### ISSUE THREAD

**Issue by julealgon** [aws/aws-lambda-dotnet#773]
## Description

When running `dotnet lambda package` for a csproj that has multitargetting enabled, a `ArgumentNullException` exception is throw and the process crashes.

Specifying the `-f` cmdline option with either `netcoreapp3.1` or `net5.0` works as expected.

I'd expect either it to work seamlessly, or to return a proper message saying that the target framework needs to be specified.

## Reproduction Steps
1. Create an API lambda project targeting Net Core 3.1 and Net 5.0

Section of csproj:
```xml
<TargetFrameworks>netcoreapp3.1;net5.0</TargetFrameworks>
```

2. Run `dotnet lambda package` in the projects folder
3. Observe exception is quickly thrown

### Logs
> Amazon Lambda Tools for .NET Core applications (5.0.0)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet
>
> Unknown error executing command: Value cannot be null.
Parameter name: paths
   at System.IO.Path.Combine(String[] paths)
   at Amazon.Lambda.Tools.LambdaPackager.CreateApplicationBundle(LambdaToolsDefaults defaults, IToolLogger logger, String workingDirectory, String projectLocation, String configuration, String targetFramework, String msbuildParameters, Boolean disableVersionCheck, LayerPackageInfo layerPackageInfo, String& publishLocation, String& zipArchivePath) in C:\codebuild\tmp\output\src845572623\src\src\Amazon.Lambda.Tools\LambdaPackager.cs:line 76
   at Amazon.Lambda.Tools.Commands.PackageCommand.PerformActionAsync()
   at Amazon.Common.DotNetCli.Tools.Commands.BaseCommand`1.ExecuteAsync() in C:\codebuild\tmp\output\src845572623\src\src\Amazon.Common.DotNetCli.Tools\Commands\BaseCommand.cs:line 46

### Environment

* OS Info: Windows 10
* Build Environment: Visual Studio 16.8.2 Developer Command Prompt,  Amazon.Lambda.Tools 5.0.0
* Targeted .NET Platform:  netcoreapp3.1 and net5.0

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @julealgon,

Good afternoon.

I was able to reproduce the issue with the steps you shared. However, I'm not sure if this is a bug since .NET Lambda needs to be packaged and published for one specific target framework/runtime. Looking at the code, looks like the .NET CLI Lambda Publish command looks only for the `TargetFramework` in one of the following ways (in the specified order):

- Checks for the `-f` or `-framework` switch in [PackageCommand.PerformActionAsync](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/4bdba759402fbea00cd5474848c01e6c451ac149/src/Amazon.Lambda.Tools/Commands/PackageCommand.cs#L193) (refer [CommandOption](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/4bdba759402fbea00cd5474848c01e6c451ac149/src/Amazon.Common.DotNetCli.Tools/Options/CommonDefinedCommandOptions.cs#L20))

- If it fails to find the target framework via command line switch, then it checks the `.csproj` file for `TargetFramework` element in [PackageCommand.PerformActionAsync](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/4bdba759402fbea00cd5474848c01e6c451ac149/src/Amazon.Lambda.Tools/Commands/PackageCommand.cs#L196) via code [Utilities.LookupTargetFrameworkFromProjectFile](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/4bdba759402fbea00cd5474848c01e6c451ac149/src/Amazon.Common.DotNetCli.Tools/Utilities.cs#L151)

As you mentioned, the 1st case works for you. I would have developer look at the issue and provide the inputs.

Thanks,
Ashish

**Comment by julealgon** [comment]
Hi @ashishdhingra 
> However, I'm not sure if this is a bug since .NET Lambda needs to be packaged and published for one specific target framework/runtime. 

I'm not saying the final behavior itself is necessarily wrong (I understand the tool probably cannot "decide for you" what target framework needs to be used), but the fact that there is a crash and a stacktrace for sure means it is an implementation bug in my view.

If the framework is always required, then the package tool should be validating this and informing the caller that he needs to explicitly set a target framework when no `TargetFramework` is present in the csproj.

Also, please keep in mind that having only a `TargetFrameworks` node and no `TargetFramework` in one's project is a common multi-targeting scenario and is fully supported in the .Net ecosystem.

---

PS: I noticed by looking at the tool implementation that no argument validation seems to be performed at the public entry point. I'd suggest starting by adding that, if possible, so that a better exception trace is returned next time a similar issue arises.

**Comment by ashishdhingra** [comment]
Hi @julealgon,

Thanks for your inputs. I was able to reproduce the issue (as you mentioned) using only the `TargetFrameworks` in the `.csproj` file and I do see it is fully supported as per Microsoft's documentation [Target frameworks in SDK-style projects](https://docs.microsoft.com/en-us/dotnet/standard/frameworks#how-to-specify-a-target-framework). I agree there should be some validation in place instead of a crash. I would discuss with developer for the inputs.

Thanks,
Ashish
