### ISSUE TITLE
Lambda Core unable to serialize Alexa Skill in-skill purchase response

### ISSUE THREAD

**Issue by jbiams77** [aws/aws-lambda-dotnet#816]
## Description
When implementing an Alexa In-Skill purchase, lambda fails when deserializing Alexa's response. My lambda function works perfectly with normal routines and only breaks when receiving a customer response from Alexa regarding In-Skill purchase. Since the lambda function is unable to deserialize the response, I am unable to capture the bug in my logs. From the Alexa Developer console, I can verify that my output from Lambda function (see below) is correct and Alexa behaves correctly.

### Exact output of my lambda function for creating the "upsell-request" to Alexa:
```{
  "version": "1.0",
  "sessionAttributes": {
    "SessionState": 0,
    "Lesson": 0,
    "LessonMode": 0,
    "LessonSkill": 0,
    "Schedule": 0,
    "TotalWordsInSession": 0,
    "FailedAttempts": 0
  },
  "response": {
    "shouldEndSession": true,
    "directives": [
      {
        "type": "Connections.SendRequest",
        "name": "Upsell",
        "token": "correlationToken",
        "payload": {
          "InSkillProduct": {
            "productId": "amzn1.adg.product.085fa670-54f4-4ccb-acc1-62208984816a"
          },
          "upsellMessage": "You currently do not have access to the word family flash cards. Would you like to hear how to get it?"
        }
      }
    ]
  }
} 
```
## Logs
Ouput received in my logs indicating the exception in:
Amazon.Lambda.Serialization.Json.JsonSerializer.Deserialize[T](Stream requestStream)

```
2021-02-21 13:36:59: Error converting the Lambda event JSON payload to type Alexa.NET.Request.SkillRequest: Value cannot be null. (Parameter 'target'): JsonSerializerException
   at Amazon.Lambda.Serialization.Json.JsonSerializer.Deserialize[T](Stream requestStream)
   at lambda_method(Closure , Stream , Stream , LambdaContextInternal )

   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.Populate(JsonReader reader, Object target)
   at Alexa.NET.Request.Type.RequestConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Amazon.Lambda.Serialization.Json.JsonSerializer.Deserialize[T](Stream requestStream)
```

### NuGet Package List
```
  <ItemGroup>
    <PackageReference Include="Alexa.NET" Version="1.15.0" />
    <PackageReference Include="Alexa.NET.APL" Version="7.1.0" />
    <PackageReference Include="Alexa.NET.InSkillPricing" Version="3.0.0" />
    <PackageReference Include="Amazon.Lambda.Core" Version="1.2.0" />
    <PackageReference Include="Amazon.Lambda.DynamoDBEvents" Version="1.2.0" />
    <PackageReference Include="Amazon.Lambda.S3Events" Version="1.2.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.8.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.1.0" />
    <PackageReference Include="AWSSDK.CognitoIdentityProvider" Version="3.5.1.14" />
    <PackageReference Include="AWSSDK.Core" Version="3.5.1.56" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.5.4.15" />
    <PackageReference Include="AWSSDK.S3" Version="3.5.7.3" />
    <PackageReference Include="AWSSDK.SQS" Version="3.5.1.5" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="System.Text.Json" Version="5.0.1" />
  </ItemGroup>
```

## Resolution
I would like to be able to capture the Alexa output that my lambda function is unable to deserialize, this make it difficult for me to debug myself.

Based on the Error, it seems the Parameter 'target' is null in Alexa.NET.Request

---

This is a :bug: bug-report

**Comment by jbiams77** [comment]
Solved the issue.
The problem is the library I'm using: ` using Alexa.NET.InSkillPricing.Responses; ` requires the addition of 
```
ConnectionRequestHandler.AddToRequestConverter();
```
This comes from a separate library:
[https://github.com/stoiveyp/Alexa.NET.InSkillPricing](url)

The problem is I was declaring that method call in the body of my function handler which comes after deserialization, hence the error. I created a function constructor to ensure this method call occurs prior to deserialization.

```
  public Function()
  {
      ConnectionRequestHandler.AddToRequestConverter();
  }
```
