### ISSUE TITLE
Docker entrypoint lambda/dotnet:5.0 not working as expected

### ISSUE THREAD

**Issue by wdolek** [aws/aws-lambda-dotnet#881]
## The Question
We are using `public.ecr.aws/lambda/dotnet:5.0` image for our AWS Lambda on .NET 5.0, this is our `Dockerfile` (redacted):

```dockerfile
FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim as build

WORKDIR /src
COPY Acme.csproj Acme/
RUN dotnet restore Acme/Acme.csproj

WORKDIR /src/Acme
COPY . .
RUN dotnet build Acme.csproj --configuration Release --output /app/build

# ---
FROM build AS publish
RUN dotnet publish Acme.csproj \
    --configuration Release \
    --runtime linux-x64 \
    --self-contained false \
    --output /app/publish \
    -p:PublishReadyToRun=true

# ---
FROM public.ecr.aws/lambda/dotnet:5.0 AS base
COPY --from=publish /app/publish /var/task/
```

Part of our CDK script:
```typescript
    const functionName = `le-function-${stage}`;

    return new Function(scope, 'le-function', {
      functionName: functionName,
      runtime: Runtime.FROM_IMAGE,
      code: Code.fromAssetImage('../src/Acme', {}),
      handler: Handler.FROM_IMAGE,
      timeout: Duration.seconds(60),
      logRetention: RetentionDays.ONE_MONTH,
    });
```

Project file (redacted):
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
    <Nullable>enable</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.APIGatewayEvents" Version="2.4.0" />
    <PackageReference Include="Amazon.Lambda.Core" Version="1.2.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.1.0" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.7.0.16" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.0.1" />
    <PackageReference Include="AWSSDK.SecurityToken" Version="3.7.1.19" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="5.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Configuration" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
```

I can deploy this function successfully, however when I try to call it (trough AWS Console, Test), I get this exception:

```
START RequestId: 7cccc389-a8ce-46ca-b4ec-bdc9c40e43e5 Version: $LATEST
Unhandled exception. System.ArgumentException: The function handler was not provided via command line arguments. (Parameter 'args')
at Amazon.Lambda.RuntimeSupport.Program.Main(String[] args) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Program.cs:line 14
at Amazon.Lambda.RuntimeSupport.Program.<Main>(String[] args)
...
```

I tried to run this function in Docker locally, but I was getting same error:
```
❯ docker run -p 9000:8080 --env AWS... /* yada yada yada */ acme:0
time="2021-06-17T15:06:04.951" level=info msg="exec '/var/lang/bin/dotnet' (cwd=/var/task, handler=/var/runtime/Amazon.Lambda.RuntimeSupport.dll)"
time="2021-06-17T15:08:34.114" level=info msg="extensionsDisabledByLayer(/opt/disable-extensions-jwigqn8j) -> stat /opt/disable-extensions-jwigqn8j: no such file or directory"
time="2021-06-17T15:08:34.114" level=warning msg="Cannot list external agents" error="open /opt/extensions: no such file or directory"
START RequestId: 6c198819-6586-4a82-916e-e5031f4cdf6a Version: $LATEST
Unhandled exception. System.ArgumentException: The function handler was not provided via command line arguments. (Parameter 'args')
   at Amazon.Lambda.RuntimeSupport.Program.Main(String[] args) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Program.cs:line 14
   at Amazon.Lambda.RuntimeSupport.Program.<Main>(String[] args)
time="2021-06-17T15:08:34.321" level=warning msg="First fatal error stored in appctx: Runtime.ExitError"
time="2021-06-17T15:08:34.321" level=warning msg="Process 17(dotnet) exited: Runtime exited with error: signal: aborted"
time="2021-06-17T15:08:34.321" level=error msg="Init failed" InvokeID= error="Runtime exited with error: signal: aborted"
time="2021-06-17T15:08:34.321" level=warning msg="Failed to send default error response: ErrInvalidInvokeID"
time="2021-06-17T15:08:34.321" level=error msg="INIT DONE failed: Runtime.ExitError"
time="2021-06-17T15:08:34.321" level=warning msg="Reset initiated: ReserveFail"
```

Exception message indicates that handler is not executed correctly, thus I added following line at the bottom of our `Dockerfile` where final image is assembled:

```dockerfile
FROM public.ecr.aws/lambda/dotnet:5.0 AS base
COPY --from=publish /app/publish /var/task/
CMD [ "Acme::Acme.LeHandler::Handle" ] # <-- added command explicitly
```

Now, Lambda works as expected, I can execute it without any issue.

I'm bit puzzled, because:

- [documentation](https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/lambda-creating-project-docker-image.html) states: _"`ENTRYPOINT`: The base image already includes an ENTRYPOINT, which is the startup process executed when the image is started."_
- when I was deploying function yesterday (2021-06-16), everything worked as expected without explicit `CMD`

❓ What could lead to such error and need of having `CMD` explicitly in `Dockerfile`? Is it possible someone changed something trouhg AWS console? Has base image changed tonight?

Thank you in advance for any explanation 🙇

**Comment by ashishdhingra** [comment]
Hi @wdolek,

Good afternoon.

Could you please check the handler in `aws-lambda-tools-defaults.json`? Also, not sure if you would want to transfer this issue to https://github.com/aws/aws-toolkit-visual-studio repository assuming that you used Visual Studio for deployment.

Thanks,
Ashish

**Comment by wdolek** [comment]
@ashishdhingra forgot to include it - it contains very same value as I had to to `CMD` (I actually copy-pasted it from there):

`aws-lambda-tools-defaults.json` (redacted):
```json
{
    "Information" : [
        "This file provides default values for the deployment wizard inside Visual Studio and the AWS Lambda commands added to the .NET Core CLI.",
        "To learn more about the Lambda commands with the .NET Core CLI execute the following command at the command line in the project root directory.",
        "dotnet lambda help",
        "All the command line options for the Lambda command can be specified in this file."
    ],
    "region": "eu-west-1",
    "configuration": "Release",
    "package-type": "Image",
    "function-memory-size": 128,
    "function-timeout": 60,
    "image-command": "Acme::Acme.LeHandler::Handle",
    "function-name": "le-function-dev",
    "function-description": "",
    "tracing-mode": "PassThrough",
    "environment-variables": "",
    "dockerfile": "Dockerfile",
    "image-tag": "aws-cdk/assets:latest",
    "profile": "default"
}
```

When you say this issue could probably belong to another project - is it relevant how `Dockerfile` looks like for each approach? I didn't even use Visual Studio.

What I tried was:
- deploying using CDK (from within our CI/CD)
- running Docker locally (no VS involved whatsoever)

Does it mean that `Dockerfile` should differ based on how I try to run it? It however doesn't explain why lambda with same `Dockerfile` worked earlier 🤷

**Comment by ashishdhingra** [comment]
Hi @wdolek,

Good morning.

I tried to reproduce the issue using the following steps:
- Created new `Lambda Empty Function (.NET 5 Container Image)` project using .NET CLI command `dotnet new lambda.image.EmptyFunction --name TestFunction`.
- This created default `Dockerfile`, `Function.cs` and `aws-lambda-tools-defaults.json`.
- Referred sample https://github.com/aws/aws-lambda-dotnet/tree/master/LambdaRuntimeDockerfiles/dotnet5/sample/Sample to modify the files as below:
- - **Dockerfile**
```

FROM public.ecr.aws/lambda/dotnet:5.0 as base

FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim as build
COPY . /TestFunction

WORKDIR /TestFunction

RUN dotnet build "TestFunction.csproj" --configuration Release --output /app/build

FROM build AS publish
RUN dotnet publish "TestFunction.csproj" \
    --configuration Release \
    --runtime linux-x64 \
    --self-contained false \
    --output /app/publish \
    -p:PublishReadyToRun=true

FROM base AS final
WORKDIR /var/task

COPY --from=publish /app/publish .
```
- - **aws-lambda-tools-defaults.json**
```JSON
{
  "Information": [
    "This file provides default values for the deployment wizard inside Visual Studio and the AWS Lambda commands added to the .NET Core CLI.",
    "To learn more about the Lambda commands with the .NET Core CLI execute the following command at the command line in the project root directory.",
    "dotnet lambda help",
    "All the command line options for the Lambda command can be specified in this file."
  ],
  "profile": "default",
  "region": "us-east-2",
  "configuration": "Release",
  "package-type": "image",
  "function-memory-size": 256,
  "function-timeout": 30,
  "function-name": "TestFunction",
  "image-command": "TestFunction::TestFunction.Function::FunctionHandler",
  "docker-host-build-output-dir": "./bin/Release/net5.0/linux-x64/publish",
  "dockerfile": "Dockerfile"
}
```
- - **Function.cs**
```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Amazon.Lambda.Core;

// Assembly attribute to enable the Lambda function's JSON input to be converted into a .NET class.
[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer))]

namespace TestFunction
{
    public class Function
    {
        
        /// <summary>
        /// A simple function that takes a string and returns both the upper and lower case version of the string.
        /// </summary>
        /// <param name="input"></param>
        /// <param name="context"></param>
        /// <returns></returns>
        public Casing FunctionHandler(string input, ILambdaContext context)
        {
            return new Casing(input?.ToLower(), input?.ToUpper());
        }
    }

    public record Casing(string Lower, string Upper);
}
```

- Ran `dotnet lambda deploy-function` from the project directory, specifying all the parameters. This deployed the new Lambda function to the region in the AWS account.
- Tested the function with parameter `"Hello World"` in AWS Console, it worked fine:
<img width="1597" alt="Screen Shot 2021-06-18 at 11 16 27 AM" src="https://user-images.githubusercontent.com/67916761/122601767-a75a9c00-d026-11eb-9572-c71210ce4e91.png">

When the `dot lambda` tool is creating the function, it applies the image properties like image command, entry point, etc. at https://github.com/aws/aws-extensions-for-dotnet-cli/blob/f6857448558c1d2f1fefb50dd1785b6b00dd37aa/src/Amazon.Lambda.Tools/Commands/DeployFunctionCommand.cs#L298.

I do notice that in AWS console Image configuration, the `CMD override` is set as `TestFunction::TestFunction.Function::FunctionHandler`.

I'm not using CDK for deployment, so not sure if it has something to do with the issue.

Thanks,
Ashish
